# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import staticpages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
        ('ad', '0002_auto_20161229_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(b'news', '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'), (b'events', '\u0421\u043e\u0431\u044b\u0442\u0438\u044f'), (b'places', '\u041c\u0435\u0441\u0442\u0430'), (b'must_know', '\u0421\u0442\u043e\u0438\u0442 \u0437\u043d\u0430\u0442\u044c'), (b'school', 'Mesto School')], db_index=True, default=b'news', max_length=15, verbose_name=b'\xd0\xba\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f')),
                ('name', models.CharField(max_length=255, verbose_name=b'\xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name=b'\xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name=b'\xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('name_hu', models.CharField(max_length=255, null=True, verbose_name=b'\xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('slug', models.SlugField(blank=True, verbose_name=b'\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd1\x8c URL-\xd0\xb0')),
                ('external_link', models.URLField(blank=True, max_length=255, verbose_name=b'\xd0\xb2\xd0\xbd\xd0\xb5\xd1\x88\xd0\xbd\xd1\x8f\xd1\x8f \xd1\x81\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('canonical', models.URLField(blank=True, max_length=100, verbose_name=b'\xd0\xba\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd1\x81\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('description', models.TextField(blank=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbd\xd1\x81\xd0\xb0')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbd\xd1\x81\xd0\xb0')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbd\xd1\x81\xd0\xb0')),
                ('description_hu', models.TextField(blank=True, null=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbd\xd1\x81\xd0\xb0')),
                ('image', models.ImageField(blank=True, upload_to=staticpages.models.make_upload_path, verbose_name=b'\xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbd\xd1\x81\xd0\xb0')),
                ('content', models.TextField(blank=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd0\xb8')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd0\xb8')),
                ('content_uk', models.TextField(blank=True, null=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd0\xb8')),
                ('content_hu', models.TextField(blank=True, null=True, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd0\xb8')),
                ('visible', models.BooleanField(default=1, verbose_name=b'\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb0\xd1\x82\xd1\x8c \xd0\xbd\xd0\xb0 \xd1\x81\xd0\xb0\xd0\xb9\xd1\x82\xd0\xb5')),
                ('xml_id', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'\xd0\xb8\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80 \xd0\xb2 XML')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name=b'\xd0\xbe\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb0')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name=b'\xd0\xb7\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb0')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\xb7\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb0')),
                ('title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\xb7\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb0')),
                ('title_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\xb7\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb0')),
                ('related', models.ManyToManyField(blank=True, related_name='_article_related_+', to='staticpages.Article', verbose_name=b'\xd1\x81\xd0\xb2\xd1\x8f\xd0\xb7\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd0\xb8')),
                ('subdomains', models.ManyToManyField(blank=True, related_name='articles', to='ad.Region', verbose_name='\u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0442\u043e\u043b\u044c\u043a\u043e \u043d\u0430 \u043f\u043e\u0434\u0434\u043e\u043c\u0435\u043d\u0430\u0445')),
            ],
            options={
                'ordering': ['-published', '-id'],
                'verbose_name': '\u0441\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='ExtendedFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_hu', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_uk', models.TextField(blank=True, null=True, verbose_name='content')),
                ('content_hu', models.TextField(blank=True, null=True, verbose_name='content')),
                ('pages_menu', models.BooleanField(default=0, verbose_name='\u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0432 \u043c\u0435\u043d\u044e \u0440\u0430\u0437\u0434\u0435\u043b\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446')),
                ('footer_menu', models.BooleanField(default=0, verbose_name='\u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0432 \u043d\u0438\u0436\u043d\u0435\u043c \u043c\u0435\u043d\u044e')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_hu', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_hu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0430\u0442\u0438\u0447\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u0438\u0447\u043d\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.CreateModel(
            name='FAQArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_hu', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(blank=True, verbose_name='\u0447\u0430\u0441\u0442\u044c URL-\u0430')),
                ('order', models.IntegerField(default=0, help_text='\u0427\u0435\u043c \u0432\u044b\u0448\u0435 \u0447\u0438\u0441\u043b\u043e, \u0442\u0435\u043c \u043d\u0438\u0436\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0437\u0430\u043f\u0438\u0441\u044c', verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f')),
                ('is_published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d?')),
                ('seo_title', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_ru', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_uk', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_hu', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_description', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_ru', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_uk', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_hu', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_keywords', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_uk', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_hu', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('content', models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('content_uk', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('content_hu', models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('video', models.CharField(blank=True, max_length=255, verbose_name='\u041a\u043e\u0434 \u0432\u0441\u0442\u0430\u0432\u043a\u0438 \u043f\u043b\u0435\u0435\u0440\u0430')),
                ('video_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u043e\u0434 \u0432\u0441\u0442\u0430\u0432\u043a\u0438 \u043f\u043b\u0435\u0435\u0440\u0430')),
                ('video_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u043e\u0434 \u0432\u0441\u0442\u0430\u0432\u043a\u0438 \u043f\u043b\u0435\u0435\u0440\u0430')),
                ('video_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u043e\u0434 \u0432\u0441\u0442\u0430\u0432\u043a\u0438 \u043f\u043b\u0435\u0435\u0440\u0430')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0441\u0442\u0430\u0442\u044c\u044e \u0434\u043b\u044f FAQ',
                'verbose_name_plural': '\u0441\u043f\u0438\u0441\u043e\u043a \u0441\u0442\u0430\u0442\u0435\u0439 \u0434\u043b\u044f FAQ',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_hu', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(blank=True, verbose_name='\u0447\u0430\u0441\u0442\u044c URL-\u0430')),
                ('order', models.IntegerField(default=0, help_text='\u0427\u0435\u043c \u0432\u044b\u0448\u0435 \u0447\u0438\u0441\u043b\u043e, \u0442\u0435\u043c \u043d\u0438\u0436\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0437\u0430\u043f\u0438\u0441\u044c', verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f')),
                ('is_published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d?')),
                ('seo_title', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_ru', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_uk', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_hu', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_description', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_ru', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_uk', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_hu', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_keywords', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_uk', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_hu', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0432\u0441\u0435\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432 \u043e\u0434\u043d\u043e\u0439 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', max_length=255, null=True, verbose_name='(SEO) Keywords')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0440\u0430\u0437\u0434\u0435\u043b \u0434\u043b\u044f FAQ',
                'verbose_name_plural': '\u0441\u043f\u0438\u0441\u043e\u043a \u0440\u0430\u0437\u0434\u0435\u043b\u043e\u0432 \u0434\u043b\u044f FAQ',
            },
        ),
        migrations.AddField(
            model_name='faqarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='staticpages.FAQCategory', verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b \u0441 \u0432\u043e\u043f\u0440\u043e\u0441\u0430\u043c\u0438'),
        ),
    ]
