# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models


def convert_flatpages_to_new_models(apps, schema_editor):
    ExtendedFlatPage = apps.get_model('staticpages', 'ExtendedFlatPage')
    ContentBlock = apps.get_model('staticpages', 'ContentBlock')
    SimplePage = apps.get_model('staticpages', 'SimplePage')

    from staticpages.translation import SimplePageTranslationOptions, ContentBlockTranslationOptions

    urls_to_rename = {
        '/about/bank/': '/about/',
        '/about/contact-bank/': '/about/contact/',
        '/about/ad-rules-bank/': '/about/ad-rules/',
    }

    urls_to_contentblock = {
        '/account/': 'account_index',
        '/import_howto/': 'import_howto',
    }

    def copy_translated_fields(flatpage, obj, fields):
        for field in fields:
            setattr(obj, field, getattr(flatpage, field))

            for postfix in ('_ru', '_uk', '_hu'):
                translation_field_name = field + postfix
                setattr(obj, translation_field_name, getattr(flatpage, translation_field_name))

    for flatpage in ExtendedFlatPage.objects.all():
        if flatpage.url in urls_to_contentblock:
            contentblock = ContentBlock(name=urls_to_contentblock[flatpage.url])
            copy_translated_fields(flatpage, contentblock, ContentBlockTranslationOptions.fields)
            contentblock.save()
        else:
            if 'bank' in flatpage.url:
                urlconf = 'bank.urls'
            else:
                urlconf = '_site.urls'

            url = urls_to_rename.get(flatpage.url) or flatpage.url

            simplepage = SimplePage(url=url, urlconf=urlconf)
            copy_translated_fields(flatpage, simplepage, SimplePageTranslationOptions.fields)
            simplepage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_remove_article_canonical'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True, null=True)),
                ('content_uk', models.TextField(blank=True, null=True)),
                ('content_hu', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u0431\u043b\u043e\u043a \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u0431\u043b\u043e\u043a\u0438 \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlconf', models.CharField(choices=[(b'_site.urls', b'_site.urls'), (b'bank.urls', b'bank.urls')], max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uk', models.CharField(max_length=200, null=True)),
                ('title_hu', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True, null=True)),
                ('content_uk', models.TextField(blank=True, null=True)),
                ('content_hu', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_hu', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_hu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0441\u0442\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u043f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.RunPython(convert_flatpages_to_new_models, migrations.RunPython.noop),
    ]
