# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_contentblock_simplepage'),
    ]

    operations = [
        # Судя по генерируемому SQL это действие дублирует действия, которые проходят в DeleteModel.
        # При этом обратная миграция не работает.
        # Баг django?
        # migrations.RemoveField(
           # model_name='extendedflatpage',
           # name='flatpage_ptr',
        # ),
        migrations.DeleteModel(
            name='ExtendedFlatPage',
        ),
    ]
