# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newhome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0434\u043e\u043c 1', max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043c\u0430')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u0434\u043e\u043c',
                'verbose_name_plural': '\u0434\u043e\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='BuildingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0447\u0435\u0440\u0435\u0434\u0438')),
                ('finish_at', models.CharField(max_length=20, verbose_name='\u041e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430')),
                ('comment', models.TextField(blank=True, help_text='\u041e\u043f\u0438\u0448\u0438\u0442\u0435 \u0432 \u0432\u043e\u043b\u044c\u043d\u043e\u0439 \u0444\u043e\u0440\u043c\u0435 \u0441\u0442\u0430\u0442\u0443\u0441 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430, \u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0434\u043e\u043c 1 \u0441\u0434\u0430\u043d, \u0432 \u0434\u043e\u043c\u0435 3 \u2014 \u0432\u0435\u0434\u0443\u0442\u0441\u044f \u043a\u043b\u0430\u0434\u043e\u0447\u043d\u044b\u0435 \u0440\u0430\u0431\u043e\u0442\u044b. ', verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0435\u043a\u0446\u0438\u0438')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='newhome.Building', verbose_name='\u0414\u043e\u043c')),
            ],
            options={
                'ordering': ('building__name', 'position'),
                'verbose_name': '\u0441\u0435\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u0441\u0435\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('site', models.URLField(blank=True, help_text='\u0430\u0434\u0440\u0435\u0441 \u0434\u043e\u043b\u0436\u0435\u043d \u043d\u0430\u0447\u0438\u043d\u0430\u0442\u044c\u0441\u044f \u0441 http://', max_length=100, null=True, verbose_name='\u0432\u0435\u0431-\u0441\u0430\u0439\u0442')),
                ('is_cabinet_enabled', models.BooleanField(default=True, verbose_name='\u0432\u043a\u043b\u044e\u0447\u0435\u043d \u043a\u0430\u0431\u0438\u043d\u0435\u0442 \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u0449\u0438\u043a\u0430?')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0433\u043e\u0440\u043e\u0434')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u0441\u0442\u0440\u043e\u0439\u0449\u0438\u043a',
                'verbose_name_plural': '\u0437\u0430\u0441\u0442\u0440\u043e\u0439\u0449\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='\u043d\u0430\u043b\u0438\u0447\u0438\u0435')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='\u0446\u0435\u043d\u0430 \u0437\u0430 \u043a\u0432\u0430\u0434\u0440\u0430\u0442\u043d\u044b\u0439 \u043c\u0435\u0442\u0440')),
            ],
            options={
                'verbose_name': '\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0430 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438',
                'verbose_name_plural': '\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: 3-9 \u044d\u0442\u0430\u0436\u0438', max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('number', models.SmallIntegerField(default=1, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u044d\u0442\u0430\u0436\u0430')),
                ('image', models.ImageField(blank=True, upload_to=newhome.models.make_floor_image_upload_path, verbose_name=b'\xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhome.Building', verbose_name='\u0434\u043e\u043c')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': '\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430 \u044d\u0442\u0430\u0436\u0430',
                'verbose_name_plural': '\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0438 \u044d\u0442\u0430\u0436\u0435\u0439',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0438', max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('rooms_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u0436\u0438\u043b\u044b\u0445 \u043a\u043e\u043c\u043d\u0430\u0442')),
                ('image', models.ImageField(blank=True, upload_to=newhome.models.make_layout_image_upload_path, verbose_name=b'\xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('area', models.DecimalField(decimal_places=2, help_text='\u043c2', max_digits=5, verbose_name='\u043e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhome.Building', verbose_name='\u0434\u043e\u043c')),
            ],
            options={
                'verbose_name': '\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430',
                'verbose_name_plural': '\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0438',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='LayoutFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField(blank=True, help_text='\u0414\u043b\u044f \u0432\u044b\u0434\u0435\u043b\u0435\u043d\u0438\u044f \u043d\u0430 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0438 \u044d\u0442\u0430\u0436\u0430', verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b')),
                ('price', models.BigIntegerField(default=0, verbose_name='\u0446\u0435\u043d\u0430')),
                ('currency', models.CharField(choices=[(b'UAH', '\u0433\u0440\u043d.'), (b'EUR', '\u20ac'), (b'USD', '$'), (b'RUR', '\u0440\u0443\u0431.')], default=b'UAH', max_length=3, verbose_name='\u0432\u0430\u043b\u044e\u0442\u0430 \u0446\u0435\u043d\u044b')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_flats', to='newhome.Floor', verbose_name='\u044d\u0442\u0430\u0436')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_flats', to='newhome.Layout', verbose_name='\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b')),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u043d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u044e')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043d\u044f\u0442\u0438\u044f \u0441 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('new_status', models.PositiveIntegerField(blank=True, choices=[(10, '\u043d\u0435\u0442 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'), (11, '\u043d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'), (12, '\u043d\u0435\u0432\u0435\u0440\u043d\u0430\u044f \u0446\u0435\u043d\u0430'), (13, '\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0438\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0438 \u0432 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0438'), (14, '\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0438\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0438 \u0432 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f\u0445'), (15, '\u0444\u043e\u0442\u043e \u043d\u0435 \u0438\u043c\u0435\u0435\u0442 \u043e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u0435 \u043a \u043e\u0431\u044a\u0435\u043a\u0442\u0443 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'), (16, '\u043d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'), (17, '\u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u0430'), (19, '\u0440\u0435\u043a\u043b\u0430\u043c\u0430'), (20, '\u0437\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043e'), (22, '\u0434\u0443\u0431\u043b\u0438\u043a\u0430\u0442 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'), (23, '\u043d\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0416\u041a'), (24, '\u043e\u0431\u044a\u0435\u043a\u0442 \u0432\u0442\u043e\u0440\u0438\u0447\u043d\u043e\u0433\u043e \u0440\u044b\u043d\u043a\u0430'), (21, '\u0440\u043e\u0431\u043e\u0442'), (200, '\u0438\u0441\u043a\u043b\u044e\u0447\u0435\u043d\u043e (\u0431\u0430\u043d)'), (220, '\u0444\u0438\u0434\u044b \u0431\u0435\u0437 \u043a\u0430\u0440\u0442\u0438\u043d\u043e\u043a')], null=True, verbose_name='\u043d\u043e\u0432\u044b\u0439 \u0441\u0442\u0430\u0442\u0443\u0441')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newhome_moderation_moderations', to=settings.AUTH_USER_MODEL, verbose_name='\u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440')),
            ],
            options={
                'ordering': ['-start_time'],
                'verbose_name': '\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Newhome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u043f\u043e\u043b\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('addr_country', models.CharField(choices=[(b'AU', b'\xd0\x90\xd0\xb2\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x8f'), (b'AT', b'\xd0\x90\xd0\xb2\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x8f'), (b'AZ', b'\xd0\x90\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb1\xd0\xb0\xd0\xb9\xd0\xb4\xd0\xb6\xd0\xb0\xd0\xbd'), (b'AL', b'\xd0\x90\xd0\xbb\xd0\xb1\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'DZ', b'\xd0\x90\xd0\xbb\xd0\xb6\xd0\xb8\xd1\x80'), (b'AI', b'\xd0\x90\xd0\xbd\xd0\xb3\xd0\xb8\xd0\xbb\xd1\x8c\xd1\x8f \xd0\xbe. (GB)'), (b'AO', b'\xd0\x90\xd0\xbd\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xb0'), (b'AD', b'\xd0\x90\xd0\xbd\xd0\xb4\xd0\xbe\xd1\x80\xd1\x80\xd0\xb0'), (b'AQ', b'\xd0\x90\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xba\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0'), (b'AG', b'\xd0\x90\xd0\xbd\xd1\x82\xd0\xb8\xd0\xb3\xd1\x83\xd0\xb0 \xd0\xb8 \xd0\x91\xd0\xb0\xd1\x80\xd0\xb1\xd1\x83\xd0\xb4\xd0\xb0'), (b'AN', b'\xd0\x90\xd0\xbd\xd1\x82\xd0\xb8\xd0\xbb\xd1\x8c\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbe-\xd0\xb2\xd0\xb0 (NL)'), (b'AR', b'\xd0\x90\xd1\x80\xd0\xb3\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8\xd0\xbd\xd0\xb0'), (b'AM', b'\xd0\x90\xd1\x80\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'), (b'AW', b'\xd0\x90\xd1\x80\xd1\x83\xd0\xb1\xd0\xb0'), (b'AF', b'\xd0\x90\xd1\x84\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'BS', b'\xd0\x91\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xbc\xd1\x8b'), (b'BD', b'\xd0\x91\xd0\xb0\xd0\xbd\xd0\xb3\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb5\xd1\x88'), (b'BB', b'\xd0\x91\xd0\xb0\xd1\x80\xd0\xb1\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81'), (b'BH', b'\xd0\x91\xd0\xb0\xd1\x85\xd1\x80\xd0\xb5\xd0\xb9\xd0\xbd'), (b'BY', b'\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c'), (b'BZ', b'\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb8\xd0\xb7'), (b'BE', b'\xd0\x91\xd0\xb5\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'), (b'BJ', b'\xd0\x91\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xbd'), (b'BM', b'\xd0\x91\xd0\xb5\xd1\x80\xd0\xbc\xd1\x83\xd0\xb4\xd1\x8b'), (b'BV', b'\xd0\x91\xd0\xbe\xd0\xb2\xd0\xb5 \xd0\xbe. (NO)'), (b'BG', b'\xd0\x91\xd0\xbe\xd0\xbb\xd0\xb3\xd0\xb0\xd1\x80\xd0\xb8\xd1\x8f'), (b'BO', b'\xd0\x91\xd0\xbe\xd0\xbb\xd0\xb8\xd0\xb2\xd0\xb8\xd1\x8f'), (b'BA', b'\xd0\x91\xd0\xbe\xd1\x81\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xb8 \xd0\x93\xd0\xb5\xd1\x80\xd1\x86\xd0\xb5\xd0\xb3\xd0\xbe\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xb0'), (b'BW', b'\xd0\x91\xd0\xbe\xd1\x82\xd1\x81\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb0'), (b'BR', b'\xd0\x91\xd1\x80\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f'), (b'BN', b'\xd0\x91\xd1\x80\xd1\x83\xd0\xbd\xd0\xb5\xd0\xb9 \xd0\x94\xd0\xb0\xd1\x80\xd0\xb0\xd1\x81\xd1\x81\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xbc'), (b'BF', b'\xd0\x91\xd1\x83\xd1\x80\xd0\xba\xd0\xb8\xd0\xbd\xd0\xb0-\xd0\xa4\xd0\xb0\xd1\x81\xd0\xbe'), (b'BI', b'\xd0\x91\xd1\x83\xd1\x80\xd1\x83\xd0\xbd\xd0\xb4\xd0\xb8'), (b'BT', b'\xd0\x91\xd1\x83\xd1\x82\xd0\xb0\xd0\xbd'), (b'VU', b'\xd0\x92\xd0\xb0\xd0\xbd\xd1\x83\xd0\xb0\xd1\x82\xd1\x83'), (b'VA', b'\xd0\x92\xd0\xb0\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0\xd0\xbd'), (b'GB', b'\xd0\x92\xd0\xb5\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb8\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'HU', b'\xd0\x92\xd0\xb5\xd0\xbd\xd0\xb3\xd1\x80\xd0\xb8\xd1\x8f'), (b'VE', b'\xd0\x92\xd0\xb5\xd0\xbd\xd0\xb5\xd1\x81\xd1\x83\xd1\x8d\xd0\xbb\xd0\xb0'), (b'VG', b'\xd0\x92\xd0\xb8\xd1\x80\xd0\xb3\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbe-\xd0\xb2\xd0\xb0 (GB)'), (b'VI', b'\xd0\x92\xd0\xb8\xd1\x80\xd0\xb3\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbe-\xd0\xb2\xd0\xb0 (US)'), (b'AS', b'\xd0\x92\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x87\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xa1\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xb0 (US)'), (b'TP', b'\xd0\x92\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x87\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xa2\xd0\xb8\xd0\xbc\xd0\xbe\xd1\x80'), (b'VN', b'\xd0\x92\xd1\x8c\xd0\xb5\xd1\x82\xd0\xbd\xd0\xb0\xd0\xbc'), (b'GA', b'\xd0\x93\xd0\xb0\xd0\xb1\xd0\xbe\xd0\xbd'), (b'HT', b'\xd0\x93\xd0\xb0\xd0\xb8\xd1\x82\xd0\xb8'), (b'GY', b'\xd0\x93\xd0\xb0\xd0\xb9\xd0\xb0\xd0\xbd\xd0\xb0'), (b'GM', b'\xd0\x93\xd0\xb0\xd0\xbc\xd0\xb1\xd0\xb8\xd1\x8f'), (b'GH', b'\xd0\x93\xd0\xb0\xd0\xbd\xd0\xb0'), (b'GP', b'\xd0\x93\xd0\xb2\xd0\xb0\xd0\xb4\xd0\xb5\xd0\xbb\xd1\x83\xd0\xbf\xd0\xb0'), (b'GT', b'\xd0\x93\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbc\xd0\xb0\xd0\xbb\xd0\xb0'), (b'GN', b'\xd0\x93\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xb5\xd1\x8f'), (b'GW', b'\xd0\x93\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xb5\xd1\x8f-\xd0\x91\xd0\xb8\xd1\x81\xd0\xb0\xd1\x83'), (b'DE', b'\xd0\x93\xd0\xb5\xd1\x80\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'GI', b'\xd0\x93\xd0\xb8\xd0\xb1\xd1\x80\xd0\xb0\xd0\xbb\xd1\x82\xd0\xb0\xd1\x80'), (b'HN', b'\xd0\x93\xd0\xbe\xd0\xbd\xd0\xb4\xd1\x83\xd1\x80\xd0\xb0\xd1\x81'), (b'HK', b'\xd0\x93\xd0\xbe\xd0\xbd\xd0\xba\xd0\xbe\xd0\xbd\xd0\xb3 (CN)'), (b'GD', b'\xd0\x93\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0\xd0\xb4\xd0\xb0'), (b'GL', b'\xd0\x93\xd1\x80\xd0\xb5\xd0\xbd\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f (DK)'), (b'GR', b'\xd0\x93\xd1\x80\xd0\xb5\xd1\x86\xd0\xb8\xd1\x8f'), (b'GE', b'\xd0\x93\xd1\x80\xd1\x83\xd0\xb7\xd0\xb8\xd1\x8f'), (b'GU', b'\xd0\x93\xd1\x83\xd0\xb0\xd0\xbc'), (b'DK', b'\xd0\x94\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'CD', b'\xd0\x94\xd0\xb5\xd0\xbc\xd0\xbe\xd0\xba\xd1\x80\xd0\xb0\xd1\x82\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xa0\xd0\xb5\xd1\x81\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0 \xd0\x9a\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xbe'), (b'DJ', b'\xd0\x94\xd0\xb6\xd0\xb8\xd0\xb1\xd1\x83\xd1\x82\xd0\xb8'), (b'DM', b'\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb0'), (b'DO', b'\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xa0\xd0\xb5\xd1\x81\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0'), (b'EG', b'\xd0\x95\xd0\xb3\xd0\xb8\xd0\xbf\xd0\xb5\xd1\x82'), (b'ZM', b'\xd0\x97\xd0\xb0\xd0\xbc\xd0\xb1\xd0\xb8\xd1\x8f'), (b'EH', b'\xd0\x97\xd0\xb0\xd0\xbf\xd0\xb0\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xa1\xd0\xb0\xd1\x85\xd0\xb0\xd1\x80\xd0\xb0'), (b'ZW', b'\xd0\x97\xd0\xb8\xd0\xbc\xd0\xb1\xd0\xb0\xd0\xb1\xd0\xb2\xd0\xb5'), (b'IL', b'\xd0\x98\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbb\xd1\x8c'), (b'IN', b'\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f'), (b'ID', b'\xd0\x98\xd0\xbd\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xb5\xd0\xb7\xd0\xb8\xd1\x8f'), (b'JO', b'\xd0\x98\xd0\xbe\xd1\x80\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'IQ', b'\xd0\x98\xd1\x80\xd0\xb0\xd0\xba'), (b'IR', b'\xd0\x98\xd1\x80\xd0\xb0\xd0\xbd'), (b'IE', b'\xd0\x98\xd1\x80\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f'), (b'IS', b'\xd0\x98\xd1\x81\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f'), (b'ES', b'\xd0\x98\xd1\x81\xd0\xbf\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'IT', b'\xd0\x98\xd1\x82\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x8f'), (b'YE', b'\xd0\x99\xd0\xb5\xd0\xbc\xd0\xb5\xd0\xbd'), (b'CV', b'\xd0\x9a\xd0\xb0\xd0\xb1\xd0\xbe-\xd0\x92\xd0\xb5\xd1\x80\xd0\xb4\xd0\xb5'), (b'KZ', b'\xd0\x9a\xd0\xb0\xd0\xb7\xd0\xb0\xd1\x85\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'KY', b'\xd0\x9a\xd0\xb0\xd0\xb9\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd1\x8b \xd0\xbe-\xd0\xb2\xd0\xb0 (GB)'), (b'KH', b'\xd0\x9a\xd0\xb0\xd0\xbc\xd0\xb1\xd0\xbe\xd0\xb4\xd0\xb6\xd0\xb0'), (b'CM', b'\xd0\x9a\xd0\xb0\xd0\xbc\xd0\xb5\xd1\x80\xd1\x83\xd0\xbd'), (b'CA', b'\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xb4\xd0\xb0'), (b'QA', b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb0\xd1\x80'), (b'KE', b'\xd0\x9a\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'), (b'CY', b'\xd0\x9a\xd0\xb8\xd0\xbf\xd1\x80'), (b'KG', b'\xd0\x9a\xd0\xb8\xd1\x80\xd0\xb3\xd0\xb8\xd0\xb7\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'KI', b'\xd0\x9a\xd0\xb8\xd1\x80\xd0\xb8\xd0\xb1\xd0\xb0\xd1\x82\xd0\xb8'), (b'CN', b'\xd0\x9a\xd0\xb8\xd1\x82\xd0\xb0\xd0\xb9'), (b'CC', b'\xd0\x9a\xd0\xbe\xd0\xba\xd0\xbe\xd1\x81\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb5 (\xd0\x9a\xd0\xb8\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb3) \xd0\xbe-\xd0\xb2\xd0\xb0 (AU)'), (b'CO', b'\xd0\x9a\xd0\xbe\xd0\xbb\xd1\x83\xd0\xbc\xd0\xb1\xd0\xb8\xd1\x8f'), (b'KM', b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbe-\xd0\xb2\xd0\xb0'), (b'CG', b'\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xbe'), (b'CR', b'\xd0\x9a\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0-\xd0\xa0\xd0\xb8\xd0\xba\xd0\xb0'), (b'CI', b"\xd0\x9a\xd0\xbe\xd1\x82-\xd0\xb4'\xd0\x98\xd0\xb2\xd1\x83\xd0\xb0\xd1\x80"), (b'CU', b'\xd0\x9a\xd1\x83\xd0\xb1\xd0\xb0'), (b'KW', b'\xd0\x9a\xd1\x83\xd0\xb2\xd0\xb5\xd0\xb9\xd1\x82'), (b'CK', b'\xd0\x9a\xd1\x83\xd0\xba\xd0\xb0 \xd0\xbe-\xd0\xb2\xd0\xb0 (NZ)'), (b'LA', b'\xd0\x9b\xd0\xb0\xd0\xbe\xd1\x81'), (b'LV', b'\xd0\x9b\xd0\xb0\xd1\x82\xd0\xb2\xd0\xb8\xd1\x8f'), (b'LS', b'\xd0\x9b\xd0\xb5\xd1\x81\xd0\xbe\xd1\x82\xd0\xbe'), (b'LR', b'\xd0\x9b\xd0\xb8\xd0\xb1\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'), (b'LB', b'\xd0\x9b\xd0\xb8\xd0\xb2\xd0\xb0\xd0\xbd'), (b'LY', b'\xd0\x9b\xd0\xb8\xd0\xb2\xd0\xb8\xd1\x8f'), (b'LT', b'\xd0\x9b\xd0\xb8\xd1\x82\xd0\xb2\xd0\xb0'), (b'LI', b'\xd0\x9b\xd0\xb8\xd1\x85\xd1\x82\xd0\xb5\xd0\xbd\xd1\x88\xd1\x82\xd0\xb5\xd0\xb9\xd0\xbd'), (b'LU', b'\xd0\x9b\xd1\x8e\xd0\xba\xd1\x81\xd0\xb5\xd0\xbc\xd0\xb1\xd1\x83\xd1\x80\xd0\xb3'), (b'MU', b'\xd0\x9c\xd0\xb0\xd0\xb2\xd1\x80\xd0\xb8\xd0\xba\xd0\xb8\xd0\xb9'), (b'MR', b'\xd0\x9c\xd0\xb0\xd0\xb2\xd1\x80\xd0\xb8\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'MG', b'\xd0\x9c\xd0\xb0\xd0\xb4\xd0\xb0\xd0\xb3\xd0\xb0\xd1\x81\xd0\xba\xd0\xb0\xd1\x80'), (b'YT', b'\xd0\x9c\xd0\xb0\xd0\xb9\xd0\xbe\xd1\x82\xd1\x82\xd0\xb0 \xd0\xbe. (KM)'), (b'MO', b'\xd0\x9c\xd0\xb0\xd0\xba\xd0\xb0\xd0\xbe (PT)'), (b'MK', b'\xd0\x9c\xd0\xb0\xd0\xba\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x8f'), (b'MW', b'\xd0\x9c\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xb8'), (b'MY', b'\xd0\x9c\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xb9\xd0\xb7\xd0\xb8\xd1\x8f'), (b'ML', b'\xd0\x9c\xd0\xb0\xd0\xbb\xd0\xb8'), (b'MV', b'\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb4\xd0\xb8\xd0\xb2\xd1\x8b'), (b'MT', b'\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb0'), (b'MA', b'\xd0\x9c\xd0\xb0\xd1\x80\xd0\xbe\xd0\xba\xd0\xba\xd0\xbe'), (b'MQ', b'\xd0\x9c\xd0\xb0\xd1\x80\xd1\x82\xd0\xb8\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb0'), (b'MH', b'\xd0\x9c\xd0\xb0\xd1\x80\xd1\x88\xd0\xb0\xd0\xbb\xd0\xbb\xd0\xbe\xd0\xb2\xd1\x8b \xd0\xbe-\xd0\xb2\xd0\xb0'), (b'MX', b'\xd0\x9c\xd0\xb5\xd0\xba\xd1\x81\xd0\xb8\xd0\xba\xd0\xb0'), (b'FM', b'\xd0\x9c\xd0\xb8\xd0\xba\xd1\x80\xd0\xbe\xd0\xbd\xd0\xb5\xd0\xb7\xd0\xb8\xd1\x8f (US)'), (b'MZ', b'\xd0\x9c\xd0\xbe\xd0\xb7\xd0\xb0\xd0\xbc\xd0\xb1\xd0\xb8\xd0\xba'), (b'MD', b'\xd0\x9c\xd0\xbe\xd0\xbb\xd0\xb4\xd0\xbe\xd0\xb2\xd0\xb0'), (b'MC', b'\xd0\x9c\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xba\xd0\xbe'), (b'MN', b'\xd0\x9c\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x8f'), (b'MS', b'\xd0\x9c\xd0\xbe\xd0\xbd\xd1\x81\xd0\xb5\xd1\x80\xd1\x80\xd0\xb0\xd1\x82 \xd0\xbe. (GB)'), (b'MM', b'\xd0\x9c\xd1\x8c\xd1\x8f\xd0\xbd\xd0\xbc\xd0\xb0'), (b'NA', b'\xd0\x9d\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xb1\xd0\xb8\xd1\x8f'), (b'NR', b'\xd0\x9d\xd0\xb0\xd1\x83\xd1\x80\xd1\x83'), (b'NP', b'\xd0\x9d\xd0\xb5\xd0\xbf\xd0\xb0\xd0\xbb'), (b'NE', b'\xd0\x9d\xd0\xb8\xd0\xb3\xd0\xb5\xd1\x80'), (b'NG', b'\xd0\x9d\xd0\xb8\xd0\xb3\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'), (b'NL', b'\xd0\x9d\xd0\xb8\xd0\xb4\xd0\xb5\xd1\x80\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x8b'), (b'NI', b'\xd0\x9d\xd0\xb8\xd0\xba\xd0\xb0\xd1\x80\xd0\xb0\xd0\xb3\xd1\x83\xd0\xb0'), (b'NU', b'\xd0\x9d\xd0\xb8\xd1\x83\xd1\x8d \xd0\xbe. (NZ)'), (b'NZ', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd0\x97\xd0\xb5\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f'), (b'NC', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd0\x9a\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xbe. (FR)'), (b'NO', b'\xd0\x9d\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x8f'), (b'NF', b'\xd0\x9d\xd0\xbe\xd1\x80\xd1\x84\xd0\xbe\xd0\xbb\xd0\xba \xd0\xbe. (AU)'), (b'AE', b'\xd0\x9e\xd0\xb1\xd1\x8a\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\x90\xd1\x80\xd0\xb0\xd0\xb1\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xad\xd0\xbc\xd0\xb8\xd1\x80\xd0\xb0\xd1\x82\xd1\x8b'), (b'OM', b'\xd0\x9e\xd0\xbc\xd0\xb0\xd0\xbd'), (b'PK', b'\xd0\x9f\xd0\xb0\xd0\xba\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'PW', b'\xd0\x9f\xd0\xb0\xd0\xbb\xd0\xb0\xd1\x83 (US)'), (b'PS', b'\xd0\x9f\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd1\x8f'), (b'PA', b'\xd0\x9f\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbc\xd0\xb0'), (b'PG', b'\xd0\x9f\xd0\xb0\xd0\xbf\xd1\x83\xd0\xb0-\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd0\x93\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xb5\xd1\x8f'), (b'PY', b'\xd0\x9f\xd0\xb0\xd1\x80\xd0\xb0\xd0\xb3\xd0\xb2\xd0\xb0\xd0\xb9'), (b'PE', b'\xd0\x9f\xd0\xb5\xd1\x80\xd1\x83'), (b'PN', b'\xd0\x9f\xd0\xb8\xd1\x82\xd0\xba\xd1\x8d\xd1\x80\xd0\xbd \xd0\xbe-\xd0\xb2\xd0\xb0 (GB)'), (b'PL', b'\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x8c\xd1\x88\xd0\xb0'), (b'PT', b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x82\xd1\x83\xd0\xb3\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x8f'), (b'PR', b'\xd0\x9f\xd1\x83\xd1\x8d\xd1\x80\xd1\x82\xd0\xbe-\xd0\xa0\xd0\xb8\xd0\xba\xd0\xbe (US)'), (b'RE', b'\xd0\xa0\xd0\xb5\xd1\x8e\xd0\xbd\xd1\x8c\xd0\xbe\xd0\xbd \xd0\xbe. (FR)'), (b'CX', b'\xd0\xa0\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb0 \xd0\xbe. (AU)'), (b'RU', b'\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'), (b'RW', b'\xd0\xa0\xd1\x83\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb0'), (b'RO', b'\xd0\xa0\xd1\x83\xd0\xbc\xd1\x8b\xd0\xbd\xd0\xb8\xd1\x8f'), (b'SV', b'\xd0\xa1\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb2\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x80'), (b'WS', b'\xd0\xa1\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xb0'), (b'SM', b'\xd0\xa1\xd0\xb0\xd0\xbd \xd0\x9c\xd0\xb0\xd1\x80\xd0\xb8\xd0\xbd\xd0\xbe'), (b'ST', b'\xd0\xa1\xd0\xb0\xd0\xbd-\xd0\xa2\xd0\xbe\xd0\xbc\xd0\xb5 \xd0\xb8 \xd0\x9f\xd1\x80\xd0\xb8\xd0\xbd\xd1\x81\xd0\xb8\xd0\xbf\xd0\xb8'), (b'SX', b'\xd0\xa1\xd0\xb8\xd0\xbd\xd1\x82-\xd0\x9c\xd0\xb0\xd1\x80\xd1\x82\xd0\xb5\xd0\xbd'), (b'SA', b'\xd0\xa1\xd0\xb0\xd1\x83\xd0\xb4\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\x90\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x8f'), (b'SZ', b'\xd0\xa1\xd0\xb2\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb4'), (b'SJ', b'\xd0\xa1\xd0\xb2\xd0\xb0\xd0\xbb\xd0\xb1\xd0\xb0\xd1\x80\xd0\xb4 \xd0\xb8 \xd0\xaf\xd0\xbd \xd0\x9c\xd0\xb5\xd0\xb9\xd0\xb5\xd0\xbd \xd0\xbe-\xd0\xb2\xd0\xb0 (NO)'), (b'SH', b'\xd0\xa1\xd0\xb2\xd1\x8f\xd1\x82\xd0\xbe\xd0\xb9 \xd0\x95\xd0\xbb\xd0\xb5\xd0\xbd\xd1\x8b \xd0\xbe. (GB)'), (b'KP', b'\xd0\xa1\xd0\xb5\xd0\xb2\xd0\xb5\xd1\x80\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x9a\xd0\xbe\xd1\x80\xd0\xb5\xd1\x8f (\xd0\x9a\xd0\x9d\xd0\x94\xd0\xa0)'), (b'MP', b'\xd0\xa1\xd0\xb5\xd0\xb2\xd0\xb5\xd1\x80\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\x9c\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbe-\xd0\xb2\xd0\xb0 (US)'), (b'SC', b'\xd0\xa1\xd0\xb5\xd0\xb9\xd1\x88\xd0\xb5\xd0\xbb\xd1\x8b'), (b'VC', b'\xd0\xa1\xd0\xb5\xd0\xbd-\xd0\x92\xd0\xb8\xd0\xbd\xd1\x81\xd0\xb5\xd0\xbd\xd1\x82 \xd0\xb8 \xd0\x93\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbd\xd1\x8b'), (b'PM', b'\xd0\xa1\xd0\xb5\xd0\xbd-\xd0\x9f\xd1\x8c\xd0\xb5\xd1\x80 \xd0\xb8 \xd0\x9c\xd0\xb8\xd0\xba\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xbd (FR)'), (b'SN', b'\xd0\xa1\xd0\xb5\xd0\xbd\xd0\xb5\xd0\xb3\xd0\xb0\xd0\xbb'), (b'KN', b'\xd0\xa1\xd0\xb5\xd0\xbd\xd1\x82-\xd0\x9a\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd1\x84\xd0\xb5\xd1\x80 \xd0\xb8 \xd0\x9d\xd0\xb5\xd0\xb2\xd0\xb8\xd1\x81'), (b'LC', b'\xd0\xa1\xd0\xb5\xd0\xbd\xd1\x82-\xd0\x9b\xd1\x8e\xd1\x81\xd0\xb8\xd1\x8f'), (b'RS', b'\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb1\xd0\xb8\xd1\x8f'), (b'SG', b'\xd0\xa1\xd0\xb8\xd0\xbd\xd0\xb3\xd0\xb0\xd0\xbf\xd1\x83\xd1\x80'), (b'SY', b'\xd0\xa1\xd0\xb8\xd1\x80\xd0\xb8\xd1\x8f'), (b'SK', b'\xd0\xa1\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xba\xd0\xb8\xd1\x8f'), (b'SI', b'\xd0\xa1\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'), (b'US', b'\xd0\xa1\xd0\xbe\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xa8\xd1\x82\xd0\xb0\xd1\x82\xd1\x8b \xd0\x90\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb8\xd0\xba\xd0\xb8'), (b'SB', b'\xd0\xa1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb2\xd1\x8b \xd0\xbe-\xd0\xb2\xd0\xb0'), (b'SO', b'\xd0\xa1\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbb\xd0\xb8'), (b'SD', b'\xd0\xa1\xd1\x83\xd0\xb4\xd0\xb0\xd0\xbd'), (b'SR', b'\xd0\xa1\xd1\x83\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb0\xd0\xbc'), (b'SL', b'\xd0\xa1\xd1\x8c\xd0\xb5\xd1\x80\xd1\x80\xd0\xb0-\xd0\x9b\xd0\xb5\xd0\xbe\xd0\xbd\xd0\xb5'), (b'TJ', b'\xd0\xa2\xd0\xb0\xd0\xb4\xd0\xb6\xd0\xb8\xd0\xba\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'TH', b'\xd0\xa2\xd0\xb0\xd0\xb8\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4'), (b'TW', b'\xd0\xa2\xd0\xb0\xd0\xb9\xd0\xb2\xd0\xb0\xd0\xbd\xd1\x8c'), (b'TZ', b'\xd0\xa2\xd0\xb0\xd0\xbd\xd0\xb7\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'), (b'TC', b'\xd0\xa2\xd0\xb5\xd1\x80\xd0\xba\xd1\x81 \xd0\xb8 \xd0\x9a\xd0\xb0\xd0\xb9\xd0\xba\xd0\xbe\xd1\x81 \xd0\xbe-\xd0\xb2\xd0\xb0 (GB)'), (b'TG', b'\xd0\xa2\xd0\xbe\xd0\xb3\xd0\xbe'), (b'TK', b'\xd0\xa2\xd0\xbe\xd0\xba\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x83 \xd0\xbe-\xd0\xb2\xd0\xb0 (NZ)'), (b'TO', b'\xd0\xa2\xd0\xbe\xd0\xbd\xd0\xb3\xd0\xb0'), (b'TT', b'\xd0\xa2\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xb4 \xd0\xb8 \xd0\xa2\xd0\xbe\xd0\xb1\xd0\xb0\xd0\xb3\xd0\xbe'), (b'TV', b'\xd0\xa2\xd1\x83\xd0\xb2\xd0\xb0\xd0\xbb\xd1\x83'), (b'TN', b'\xd0\xa2\xd1\x83\xd0\xbd\xd0\xb8\xd1\x81'), (b'TM', b'\xd0\xa2\xd1\x83\xd1\x80\xd0\xba\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'TR', b'\xd0\xa2\xd1\x83\xd1\x80\xd1\x86\xd0\xb8\xd1\x8f'), (b'UG', b'\xd0\xa3\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb0'), (b'UZ', b'\xd0\xa3\xd0\xb7\xd0\xb1\xd0\xb5\xd0\xba\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'), (b'UA', b'\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'), (b'WF', b'\xd0\xa3\xd0\xbe\xd0\xbb\xd0\xbb\xd0\xb8\xd1\x81 \xd0\xb8 \xd0\xa4\xd1\x83\xd1\x82\xd1\x83\xd0\xbd\xd0\xb0 \xd0\xbe-\xd0\xb2\xd0\xb0 (FR)'), (b'UY', b'\xd0\xa3\xd1\x80\xd1\x83\xd0\xb3\xd0\xb2\xd0\xb0\xd0\xb9'), (b'FO', b'\xd0\xa4\xd0\xb0\xd1\x80\xd0\xb5\xd1\x80\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbe-\xd0\xb2\xd0\xb0 (DK)'), (b'FJ', b'\xd0\xa4\xd0\xb8\xd0\xb4\xd0\xb6\xd0\xb8'), (b'PH', b'\xd0\xa4\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xbf\xd0\xbf\xd0\xb8\xd0\xbd\xd1\x8b'), (b'FI', b'\xd0\xa4\xd0\xb8\xd0\xbd\xd0\xbb\xd1\x8f\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f'), (b'FK', b'\xd0\xa4\xd0\xbe\xd0\xbb\xd0\xba\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb4\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 (\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb2\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5) \xd0\xbe-\xd0\xb2\xd0\xb0 (GB/AR)'), (b'FR', b'\xd0\xa4\xd1\x80\xd0\xb0\xd0\xbd\xd1\x86\xd0\xb8\xd1\x8f'), (b'GF', b'\xd0\xa4\xd1\x80\xd0\xb0\xd0\xbd\xd1\x86\xd1\x83\xd0\xb7\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\x93\xd0\xb2\xd0\xb8\xd0\xb0\xd0\xbd\xd0\xb0 (FR)'), (b'PF', b'\xd0\xa4\xd1\x80\xd0\xb0\xd0\xbd\xd1\x86\xd1\x83\xd0\xb7\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\x9f\xd0\xbe\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb5\xd0\xb7\xd0\xb8\xd1\x8f'), (b'HM', b'\xd0\xa5\xd0\xb5\xd1\x80\xd0\xb4 \xd0\xb8 \xd0\x9c\xd0\xb0\xd0\xba\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb4 \xd0\xbe-\xd0\xb2\xd0\xb0 (AU)'), (b'HR', b'\xd0\xa5\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb8\xd1\x8f'), (b'CF', b'\xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe-\xd0\xb0\xd1\x84\xd1\x80\xd0\xb8\xd0\xba\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xa0\xd0\xb5\xd1\x81\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0'), (b'TD', b'\xd0\xa7\xd0\xb0\xd0\xb4'), (b'ME', b'\xd0\xa7\xd0\xb5\xd1\x80\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'), (b'CZ', b'\xd0\xa7\xd0\xb5\xd1\x85\xd0\xb8\xd1\x8f'), (b'CL', b'\xd0\xa7\xd0\xb8\xd0\xbb\xd0\xb8'), (b'CH', b'\xd0\xa8\xd0\xb2\xd0\xb5\xd0\xb9\xd1\x86\xd0\xb0\xd1\x80\xd0\xb8\xd1\x8f'), (b'SE', b'\xd0\xa8\xd0\xb2\xd0\xb5\xd1\x86\xd0\xb8\xd1\x8f'), (b'LK', b'\xd0\xa8\xd1\x80\xd0\xb8-\xd0\x9b\xd0\xb0\xd0\xbd\xd0\xba\xd0\xb0'), (b'EC', b'\xd0\xad\xd0\xba\xd0\xb2\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x80'), (b'GQ', b'\xd0\xad\xd0\xba\xd0\xb2\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x93\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xb5\xd1\x8f'), (b'ER', b'\xd0\xad\xd1\x80\xd0\xb8\xd1\x82\xd1\x80\xd0\xb8\xd1\x8f'), (b'EE', b'\xd0\xad\xd1\x81\xd1\x82\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x8f'), (b'ET', b'\xd0\xad\xd1\x84\xd0\xb8\xd0\xbe\xd0\xbf\xd0\xb8\xd1\x8f'), (b'YU', b'\xd0\xae\xd0\xb3\xd0\xbe\xd1\x81\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x8f'), (b'ZA', b'\xd0\xae\xd0\xb6\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x90\xd1\x84\xd1\x80\xd0\xb8\xd0\xba\xd0\xb0'), (b'GS', b'\xd0\xae\xd0\xb6\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x93\xd0\xb5\xd0\xbe\xd1\x80\xd0\xb3\xd0\xb8\xd1\x8f \xd0\xb8 \xd0\xae\xd0\xb6\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xa1\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb2\xd0\xb8\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b \xd0\xbe-\xd0\xb2\xd0\xb0'), (b'KR', b'\xd0\xae\xd0\xb6\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x9a\xd0\xbe\xd1\x80\xd0\xb5\xd1\x8f (\xd0\xa0\xd0\xb5\xd1\x81\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0 \xd0\x9a\xd0\xbe\xd1\x80\xd0\xb5\xd1\x8f)'), (b'JM', b'\xd0\xaf\xd0\xbc\xd0\xb0\xd0\xb9\xd0\xba\xd0\xb0'), (b'JP', b'\xd0\xaf\xd0\xbf\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x8f')], default=b'UA', max_length=2, verbose_name='\u0441\u0442\u0440\u0430\u043d\u0430')),
                ('addr_city', models.CharField(max_length=100, null=True, verbose_name='\u043d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442')),
                ('addr_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0443\u043b\u0438\u0446\u0430')),
                ('addr_house', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0434\u043e\u043c\u0430')),
                ('geo_source', models.CharField(choices=[(b'addr', '\u043f\u043e\u043b\u044f \u0430\u0434\u0440\u0435\u0441\u0430'), (b'coords', '\u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b'), (b'addr_coords', '\u043f\u043e\u043b\u044f \u0430\u0434\u0440\u0435\u0441\u0430 \u0438 \u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b')], default=b'addr', max_length=15, verbose_name='\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u043c\u0435\u0441\u0442\u043e\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u044f')),
                ('coords_x', models.FloatField(blank=True, null=True, verbose_name='\u0434\u043e\u043b\u0433\u043e\u0442\u0430/longitude')),
                ('coords_y', models.FloatField(blank=True, null=True, verbose_name='\u0448\u0438\u0440\u043e\u0442\u0430/latitude')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('is_published', models.BooleanField(default=False, verbose_name='\u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('status', models.PositiveIntegerField(choices=[(1, '\u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'), (210, '\u043d\u0435\u0430\u043a\u0442\u0438\u0432\u043d\u043e'), (211, '\u0443\u0434\u0430\u043b\u0435\u043d\u043e')], default=210, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441')),
                ('moderation_status', models.PositiveIntegerField(blank=True, choices=[(10, '\u043d\u0435\u0442 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'), (11, '\u043d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'), (12, '\u043d\u0435\u0432\u0435\u0440\u043d\u0430\u044f \u0446\u0435\u043d\u0430'), (13, '\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0438\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0438 \u0432 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0438'), (14, '\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0438\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0438 \u0432 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f\u0445'), (15, '\u0444\u043e\u0442\u043e \u043d\u0435 \u0438\u043c\u0435\u0435\u0442 \u043e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u0435 \u043a \u043e\u0431\u044a\u0435\u043a\u0442\u0443 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'), (16, '\u043d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c'), (17, '\u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u0430'), (19, '\u0440\u0435\u043a\u043b\u0430\u043c\u0430'), (20, '\u0437\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043e'), (22, '\u0434\u0443\u0431\u043b\u0438\u043a\u0430\u0442 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'), (23, '\u043d\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0416\u041a'), (24, '\u043e\u0431\u044a\u0435\u043a\u0442 \u0432\u0442\u043e\u0440\u0438\u0447\u043d\u043e\u0433\u043e \u0440\u044b\u043d\u043a\u0430'), (21, '\u0440\u043e\u0431\u043e\u0442'), (200, '\u0438\u0441\u043a\u043b\u044e\u0447\u0435\u043d\u043e (\u0431\u0430\u043d)'), (220, '\u0444\u0438\u0434\u044b \u0431\u0435\u0437 \u043a\u0430\u0440\u0442\u0438\u043d\u043e\u043a')], null=True, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('fields_for_moderation', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u043f\u043e\u043b\u044f, \u0442\u0440\u0435\u0431\u0443\u044e\u0449\u0438\u0435 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438 \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('priority_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442\u043d\u044b\u0439 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 e-mail, \u0435\u0441\u043b\u0438 \u043e\u0442\u043b\u0438\u0447\u0430\u0435\u0442\u0441\u044f \u043e\u0442 \u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0433\u043e')),
                ('name', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u043a')),
                ('name_ru', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u043a')),
                ('name_uk', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u043a')),
                ('name_hu', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435', max_length=100, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0436\u043a')),
                ('keywords', models.TextField(blank=True, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442\u0441\u044f \u0434\u043b\u044f \u0443\u043b\u0443\u0447\u0448\u0435\u043d\u0438\u044f \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0430 \u043f\u043e\u0438\u0441\u043a\u0430. \u0423\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('keywords_ru', models.TextField(blank=True, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442\u0441\u044f \u0434\u043b\u044f \u0443\u043b\u0443\u0447\u0448\u0435\u043d\u0438\u044f \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0430 \u043f\u043e\u0438\u0441\u043a\u0430. \u0423\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', null=True, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('keywords_uk', models.TextField(blank=True, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442\u0441\u044f \u0434\u043b\u044f \u0443\u043b\u0443\u0447\u0448\u0435\u043d\u0438\u044f \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0430 \u043f\u043e\u0438\u0441\u043a\u0430. \u0423\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', null=True, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('keywords_hu', models.TextField(blank=True, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442\u0441\u044f \u0434\u043b\u044f \u0443\u043b\u0443\u0447\u0448\u0435\u043d\u0438\u044f \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0430 \u043f\u043e\u0438\u0441\u043a\u0430. \u0423\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', null=True, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('newhome_type', models.CharField(choices=[(b'buildings', '\u0416\u0438\u043b\u0438\u0449\u043d\u044b\u0439 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0441'), (b'home', '\u0414\u043e\u043c')], default=b'buildings', max_length=20, verbose_name='\u0442\u0438\u043f')),
                ('price_at', models.PositiveIntegerField(default=0, verbose_name='\u0446\u0435\u043d\u0430 \u0437\u0430 \u043c<sup>2</sup>, \u043e\u0442 (\u0432 \u0433\u0440\u0438\u0432\u043d\u0430\u0445)')),
                ('building_class', models.CharField(choices=[(b'econom', '\u044d\u043a\u043e\u043d\u043e\u043c'), (b'comfort', '\u043a\u043e\u043c\u0444\u043e\u0440\u0442'), (b'business', '\u0431\u0438\u0437\u043d\u0435\u0441'), (b'elite', '\u043f\u0440\u0435\u043c\u0438\u0443\u043c')], max_length=10, verbose_name='\u043a\u043b\u0430\u0441\u0441')),
                ('developer', models.CharField(max_length=50, verbose_name='\u0440\u0435\u0430\u043b\u0438\u0437\u0443\u0435\u0442')),
                ('developer_ru', models.CharField(max_length=50, null=True, verbose_name='\u0440\u0435\u0430\u043b\u0438\u0437\u0443\u0435\u0442')),
                ('developer_uk', models.CharField(max_length=50, null=True, verbose_name='\u0440\u0435\u0430\u043b\u0438\u0437\u0443\u0435\u0442')),
                ('developer_hu', models.CharField(max_length=50, null=True, verbose_name='\u0440\u0435\u0430\u043b\u0438\u0437\u0443\u0435\u0442')),
                ('website', models.URLField(blank=True, help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u0430\u0439\u0442 \u0416\u041a', max_length=100, verbose_name='\u043f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('content', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, help_text='\u0432 \u043c\u0435\u0442\u0440\u0430\u0445', max_digits=4, null=True, verbose_name='\u0432\u044b\u0441\u043e\u0442\u0430 \u043f\u043e\u0442\u043e\u043b\u043a\u043e\u0432')),
                ('buildings_total', models.PositiveSmallIntegerField(blank=True, help_text='\u043a\u043e\u043b-\u0432\u043e \u0434\u043e\u043c\u043e\u0432 \u0432 \u0416\u041a', null=True, verbose_name='\u0434\u043e\u043c\u043e\u0432')),
                ('flats_total', models.PositiveSmallIntegerField(blank=True, help_text='\u0441\u0443\u043c\u043c\u0430 \u043f\u043e \u0432\u0441\u0435\u043c \u0434\u043e\u043c\u0430\u043c', null=True, verbose_name='\u043a\u0432\u0430\u0440\u0442\u0438\u0440 \u0432 \u0416\u041a')),
                ('heating', models.CharField(choices=[(b'auto', '\u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0435'), (b'central', '\u0446\u0435\u043d\u0442\u0440\u0430\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u043e\u0435')], default='central', max_length=255, verbose_name='\u043e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u0435')),
                ('phases', models.PositiveSmallIntegerField(blank=True, help_text='\u0432\u0441\u0435\u0433\u043e \u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439 \u043f\u043e \u0416\u041a', null=True, verbose_name='\u043e\u0447\u0435\u0440\u0435\u0434\u0435\u0439')),
                ('parking_info', models.CharField(choices=[(b'underground', '\u043f\u043e\u0434\u0437\u0435\u043c\u043d\u044b\u0439'), (b'ground', '\u043d\u0430\u0437\u0435\u043c\u043d\u044b\u0439'), (b'none', '\u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442')], default='none', max_length=255, verbose_name='\u043f\u0430\u0440\u043a\u0438\u043d\u0433')),
                ('walls', models.CharField(blank=True, choices=[(b'wall01', '\u043a\u0438\u0440\u043f\u0438\u0447'), (b'wall02', '\u043b\u0435\u0433\u043a\u043e\u0431\u0435\u0442\u043e\u043d\u043d\u044b\u0435 \u0431\u043b\u043e\u043a\u0438'), (b'wall03', '\u043a\u0435\u0440\u0430\u043c\u043e\u0431\u043b\u043e\u043a'), (b'wall04', '\u0435\u0441\u0442\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0439 \u043a\u0430\u043c\u0435\u043d\u044c'), (b'wall05', '\u0434\u0435\u0440\u0435\u0432\u043e')], max_length=255, verbose_name='\u0441\u0442\u0435\u043d\u044b')),
                ('building_insulation', models.CharField(blank=True, choices=[(b'yes', '\u0435\u0441\u0442\u044c'), (b'no', '\u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442')], max_length=255, verbose_name='\u0443\u0442\u0435\u043f\u043b\u0435\u043d\u0438\u0435')),
                ('number_of_floors', models.CharField(blank=True, help_text='\u044d\u0442\u0430\u0436\u0435\u0439 \u0432 \u0434\u043e\u043c\u0435', max_length=255, verbose_name='\u044d\u0442\u0430\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('priority_phones', models.ManyToManyField(blank=True, related_name='priority_phones', to='ad.Phone', verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442\u043d\u044b\u0439 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d, \u0435\u0441\u043b\u0438 \u043e\u0442\u043b\u0438\u0447\u0430\u0435\u0442\u0441\u044f \u043e\u0442 \u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0433\u043e')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_newhome', to='ad.Region', verbose_name='\u043f\u0440\u0438\u0441\u0432\u043e\u0435\u043d\u043d\u044b\u0439 \u0440\u0435\u0433\u0438\u043e\u043d')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newhomes', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430',
                'verbose_name_plural': '\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
                'permissions': (('newhome_admin', '\u0420\u0430\u0441\u0448\u0438\u0440\u0435\u043d\u043d\u044b\u0435 \u043f\u0440\u0430\u0432\u0430 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0435\u043a'), ('newhome_moderation', '\u041c\u043e\u0434\u0435\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0435\u043a'), ('newhome_notification', '\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f \u043e \u043f\u0440\u043e\u0444\u0438\u043b\u044f\u0445 \u0437\u0430\u0441\u0442\u0440\u043e\u0439\u0449\u0438\u043a\u043e\u0432 / \u043b\u0438\u0434\u043e\u0432')),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewhomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=newhome.models.make_newhomephoto_image_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('is_main', models.BooleanField(default=False, verbose_name='\u043e\u0441\u043d\u043e\u0432\u043d\u0430\u044f?')),
                ('newhome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newhome_photos', to='newhome.Newhome', verbose_name='\u0436\u043a')),
            ],
            options={
                'ordering': ('-is_main', 'id'),
                'verbose_name': '\u0444\u043e\u0442\u043e \u0436\u043a',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e \u0436\u043a',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0447\u0435\u0440\u0435\u0434\u0438/\u0434\u043e\u043c\u0430')),
                ('newhome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': '\u043e\u0442\u0447\u0435\u0442 \u043e \u0445\u043e\u0434\u0435 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430',
                'verbose_name_plural': '\u043e\u0442\u0447\u0435\u0442\u044b \u043e \u0445\u043e\u0434\u0435 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=newhome.models.make_progressphoto_image_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='newhome.Progress', verbose_name='\u043e\u0442\u0447\u0435\u0442 \u043e \u0445\u043e\u0434\u0435 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e \u0434\u043b\u044f \u043e\u0442\u0447\u0435\u0442\u043e\u0432',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e \u0434\u043b\u044f \u043e\u0442\u0447\u0435\u0442\u043e\u0432',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_num', models.CharField(blank=True, help_text='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u043d\u0430 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0438', max_length=5, verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('name', models.CharField(blank=True, help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043c\u043d\u0430\u0442\u044b', max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='\u043a\u0432. \u043c', max_digits=5, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='newhome.Layout', verbose_name='\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '\u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('type', models.PositiveIntegerField(choices=[(0, '\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'), (1, '\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043e\u0432'), (2, '\u0444\u043e\u0440\u043c\u0430 \u043d\u0430\u043b\u0438\u0447\u0438\u044f \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438')], db_index=True, default=0, verbose_name='\u0442\u0438\u043f \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
                ('views', models.PositiveIntegerField(default=1, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432')),
                ('newhome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewscounts', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043e\u0431\u044a\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='moderation',
            name='newhome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newhome_moderations', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='layout',
            name='newhome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='layout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhome.BuildingSection', verbose_name='\u0441\u0435\u043a\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='floor',
            name='layouts',
            field=models.ManyToManyField(to='newhome.Layout', verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='floor',
            name='newhome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='floor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhome.BuildingSection', verbose_name='\u0441\u0435\u043a\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhome.Floor', verbose_name='\u044d\u0442\u0430\u0436'),
        ),
        migrations.AddField(
            model_name='flat',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newhome.Layout', verbose_name='\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='flat',
            name='newhome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='buildingqueue',
            name='newhome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='buildingqueue',
            name='sections',
            field=models.ManyToManyField(to='newhome.BuildingSection', verbose_name='\u0414\u043e\u043c\u0430 \u0438 \u0441\u0435\u043a\u0446\u0438\u0438 \u0434\u043b\u044f \u043e\u0447\u0435\u0440\u0435\u0434\u0438'),
        ),
        migrations.AddField(
            model_name='building',
            name='newhome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='newhome.Newhome', verbose_name='\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0430'),
        ),
    ]
