# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_auto_20170607_1333'),
        ('newhome', '0005_auto_20170405_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='basead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newhome_layouts', to='ad.BaseAd', verbose_name='\u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c'),
        ),
    ]
