# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 12:46
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Photo = apps.get_model('ad', 'Photo')
    Ad = apps.get_model('ad', 'Ad')
    Layout = apps.get_model('newhome', 'Layout')

    newhomes_id = set(Ad.objects.filter(
        newhome_layout__isnull=False).values_list('newhome_layout__newhome_id', flat=True))

    # Аггрегируем по объектам ЖК
    for position, newhome_id in enumerate(newhomes_id):
        layouts_id = list(Ad.objects.filter(
            newhome_layout__newhome__id=newhome_id).values_list('newhome_layout_id', flat=True))

        available_rooms_amount = set(Layout.objects.filter(id__in=layouts_id).values_list('rooms_total', flat=True))

        # Дальнейшая аггрегация по количеству-комнат
        for room_amount in available_rooms_amount:
            layouts = Layout.objects.filter(id__in=layouts_id, rooms_total=room_amount)
            base_layout = layouts.first()
            base_ad = Ad.objects.get(newhome_layout=base_layout)

            duplicate_layouts_id = list(layouts.exclude(id=base_layout.id).values_list('id', flat=True))
            if duplicate_layouts_id:
                base_ad_photo_hashes = list(base_ad.photos.values_list('hash', flat=True))

                # Переносим фото в базовое объявление
                Photo.objects.filter(basead__ad__newhome_layout__id__in=duplicate_layouts_id).exclude(
                    hash__in=base_ad_photo_hashes).update(basead=base_ad.pk)

                # Все дублирующие объявления помечаем как удаленные и снимаем с публикации
                Ad.objects.filter(newhome_layout__id__in=duplicate_layouts_id).update(status=211, is_published=False)

            # Планировки выбранного ЖК с текущим кол-вом комнат привязываем к базовому объявлению
            Layout.objects.filter(rooms_total=room_amount, newhome=base_layout.newhome_id).update(basead=base_ad.pk)

        # Обнуляем ныне неиспользуемое поле привязки объявления к планировке
        Ad.objects.filter(newhome_layout__id__in=layouts_id).update(newhome_layout=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_auto_20170607_1333'),
        ('newhome', '0006_layout_basead'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
