# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAdTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u0430\u043b\u0430')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430')),
                ('xml', models.TextField(verbose_name='\u0444\u0440\u0430\u0433\u043c\u0435\u043d\u0442 \u0444\u0430\u0439\u043b\u0430')),
                ('raw_xml_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0438\u043d\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0432 \u0444\u0430\u0439\u043b\u0435')),
                ('status', models.CharField(choices=[(b'waiting', '\u043e\u0436\u0438\u0434\u0430\u0435\u0442'), (b'processing', '\u0432\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f'), (b'completed', '\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430')], default=b'waiting', max_length=20, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='\u043e\u0448\u0438\u0431\u043a\u0438')),
                ('action', models.CharField(blank=True, choices=[(b'add', '\u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435'), (b'update', '\u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435')], max_length=20, null=True, verbose_name='\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435')),
                ('report', models.TextField(null=True, verbose_name='\u0444\u0440\u0430\u0433\u043c\u0435\u043d\u0442 \u043e\u0442\u0447\u0435\u0442\u0430')),
                ('basead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importadtasks', to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u0434\u0430\u0447\u0430 \u0438\u043c\u043f\u043e\u0440\u0442\u0430 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0437\u0430\u0434\u0430\u0447\u0438 \u0438\u043c\u043f\u043e\u0440\u0442\u0430 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0444\u0430\u0439\u043b')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='\u0441\u0442\u0430\u0440\u0442\u043e\u0432\u0430\u043b\u0430')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430')),
                ('status', models.CharField(choices=[(b'waiting', '\u043e\u0436\u0438\u0434\u0430\u0435\u0442'), (b'processing', '\u0432\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f'), (b'waiting_for_importadtasks', '\u043e\u0436\u0438\u0434\u0430\u0435\u0442 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u043f\u043e\u0434\u0437\u0430\u0434\u0430\u0447'), (b'completed', '\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430')], default=b'waiting', max_length=30, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441')),
                ('error', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u043e\u0448\u0438\u0431\u043a\u0430')),
                ('stats', jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430')),
                ('is_test', models.BooleanField(default=False, verbose_name='\u0442\u0435\u0441\u0442?')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importtasks', to='agency.Agency', verbose_name='\u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u043e')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u0434\u0430\u0447\u0430 \u0438\u043c\u043f\u043e\u0440\u0442\u0430',
                'verbose_name_plural': '\u0437\u0430\u0434\u0430\u0447\u0438 \u0438\u043c\u043f\u043e\u0440\u0442\u0430',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.AddField(
            model_name='importadtask',
            name='importtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importadtasks', to='import_.ImportTask', verbose_name='\u0437\u0430\u0434\u0430\u0447\u0430 \u0438\u043c\u043f\u043e\u0440\u0442\u0430'),
        ),
    ]
