# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsteriskCdr',
            fields=[
                ('calldate', models.DateTimeField(verbose_name='\u0432\u0440\u0435\u043c\u044f')),
                ('clid', models.CharField(max_length=80, verbose_name='Caller ID \u0432\u044b\u0437\u044b\u0432\u0430\u044e\u0449\u0435\u0433\u043e \u0430\u0431\u043e\u043d\u0435\u043d\u0442\u0430')),
                ('src', models.CharField(max_length=80, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0432\u044b\u0437\u044b\u0432\u0430\u044e\u0449\u0435\u0433\u043e \u0430\u0431\u043e\u043d\u0435\u043d\u0442\u0430')),
                ('dst', models.CharField(max_length=80, verbose_name='\u043f\u0443\u043d\u043a\u0442 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u0432\u044b\u0437\u043e\u0432\u0430')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0432\u044b\u0437\u043e\u0432\u0430')),
                ('billsec', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u044f \u0441 \u043c\u043e\u043c\u0435\u043d\u0442\u0430 \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('disposition', models.CharField(max_length=45, verbose_name='\u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u0432\u044b\u0437\u043e\u0432\u0430')),
                ('uniqueid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('userfield', models.CharField(max_length=255, verbose_name='\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043f\u0438\u0441\u044c \u0430\u0441\u0442\u0435\u0440\u0438\u0441\u043a\u0430',
                'db_table': 'cdr',
                'managed': False,
                'verbose_name_plural': '\u0437\u0430\u043f\u0438\u0441\u0438 \u0430\u0441\u0442\u0435\u0440\u0438\u0441\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(db_index=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0437\u0432\u043e\u043d\u043a\u0430')),
                ('answer_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u0442\u0432\u0435\u0442\u0430 \u043d\u0430 \u0437\u0432\u043e\u043d\u043e\u043a')),
                ('hang_up_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435 \u0437\u0432\u043e\u043d\u043a\u0430')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0440\u0430\u0437\u0433\u043e\u0432\u043e\u0440\u0430')),
                ('callerid1', models.CharField(default=b'', max_length=14, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0437\u0432\u043e\u043d\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('uniqueid1', models.CharField(db_index=True, default=b'', max_length=40, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0432\u043e\u043d\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('callerid2', models.CharField(blank=True, default=b'', max_length=14, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043e\u0442\u0432\u0435\u0442\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('uniqueid2', models.CharField(blank=True, db_index=True, default=b'', max_length=40, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043e\u0442\u0432\u0435\u0442\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('subject', models.PositiveIntegerField(blank=True, choices=[(1, '\u043e\u0431\u0449\u0438\u0435 \u0432\u043e\u043f\u0440\u043e\u0441\u044b'), (2, '\u0432\u043e\u043f\u0440\u043e\u0441\u044b \u043f\u043e \u043e\u043f\u043b\u0430\u0442\u0435'), (3, '\u0432\u043e\u043f\u0440\u043e\u0441\u044b \u043f\u043e \u0443\u0441\u043b\u0443\u0433\u0430\u043c'), (4, '\u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u044f \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439'), (5, '\u0431\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0430\u044f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c')], null=True, verbose_name='\u0442\u0435\u043c\u0430 \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0437\u0432\u043e\u043d\u043e\u043a',
                'verbose_name_plural': '\u0437\u0432\u043e\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='ManagerCallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol=b'IPv4', verbose_name='IP \u0430\u0434\u0440\u0435\u0441 \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('subject', models.PositiveIntegerField(blank=True, choices=[(1, '\u043e\u0431\u0449\u0438\u0435 \u0432\u043e\u043f\u0440\u043e\u0441\u044b'), (2, '\u0432\u043e\u043f\u0440\u043e\u0441\u044b \u043f\u043e \u043e\u043f\u043b\u0430\u0442\u0435'), (3, '\u0432\u043e\u043f\u0440\u043e\u0441\u044b \u043f\u043e \u0443\u0441\u043b\u0443\u0433\u0430\u043c'), (4, '\u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u044f \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439'), (5, '\u0431\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0430\u044f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c')], null=True, verbose_name='\u0442\u0435\u043c\u0430 \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043f\u0440\u043e\u0441 \u0437\u0432\u043e\u043d\u043a\u0430',
                'verbose_name_plural': '\u0437\u0430\u043f\u0440\u043e\u0441\u044b \u0437\u0432\u043e\u043d\u043a\u0430',
            },
        ),
    ]
