# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u043d\u043a\u0430')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=bank.models.make_upload_path, verbose_name='\u043b\u043e\u0433\u043e\u0442\u0438\u043f')),
                ('financing_conditions', models.TextField(blank=True, null=True, verbose_name='\u0443\u0441\u043b\u043e\u0432\u0438\u044f \u0444\u0438\u043d\u0430\u043d\u0441\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439?')),
            ],
            options={
                'verbose_name': '\u0431\u0430\u043d\u043a',
                'verbose_name_plural': '\u0431\u0430\u043d\u043a\u0438',
            },
        ),
    ]
