# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newhome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_moderation_moderations', to=settings.AUTH_USER_MODEL, verbose_name='\u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='facility',
            name='deal_type',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='ad.DealType', verbose_name='\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0432 \u0442\u0438\u043f\u0430\u0445 \u0441\u0434\u0435\u043b\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='basead',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='_basead_facilities_+', to='ad.Facility', verbose_name='\u0443\u0434\u043e\u0431\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='basead',
            name='phones',
            field=models.ManyToManyField(related_name='ads', through='ad.PhoneInAd', to='ad.Phone', verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
        migrations.AddField(
            model_name='basead',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='_basead_rules_+', to='ad.Rules', verbose_name='\u043f\u0440\u0430\u0432\u0438\u043b\u0430 \u0437\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterUniqueTogether(
            name='phoneinad',
            unique_together=set([('phone', 'basead')]),
        ),
        migrations.AddField(
            model_name='ad',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='bank.Bank', verbose_name='\u0431\u0430\u043d\u043a'),
        ),
        migrations.AddField(
            model_name='ad',
            name='newhome_layout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newhome_layout', to='newhome.Layout'),
        ),
        migrations.AddField(
            model_name='ad',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_ad', to='ad.Region', verbose_name='\u043f\u0440\u0438\u0441\u0432\u043e\u0435\u043d\u043d\u044b\u0439 \u0440\u0435\u0433\u0438\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterIndexTogether(
            name='ad',
            index_together=set([('user', 'created'), ('status', 'deal_type', 'region', 'property_type', 'rooms'), ('status', 'deal_type', 'region', 'has_photos')]),
        ),
    ]
