# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_partitioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtype',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='dealtype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='dealtype',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
