# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_auto_20170112_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='\u043e\u0431\u044a\u0435\u043a\u0442 \u043f\u0440\u043e\u0434\u0430\u043d'),
        ),
    ]
