# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:52
from __future__ import unicode_literals

from django.db import migrations


def create_initial_regions_for_nesto(apps, schema_editor):
    from django.conf import settings
    from utils import ymaps_api
    from ad.models import Ad, Region

    if settings.MESTO_SITE == 'nesto':
        geocode_reverse = ymaps_api.geocode_reverse('19.055073, 47.499715')
        address_arr = []

        for addr in geocode_reverse:
            kind = addr[0]

            if kind in ['country', 'province', 'locality']:
                address_arr.append(addr)

        Ad._fill_region_from_address_detail(address_arr[::-1])

        Region.objects.filter(kind='province').update(price_level='high')

        Region.objects.filter(kind='country').update(subdomain=True)  # отдельно от поля static_url, иначе оно обновится в pre_save
        hungary = Region.objects.get(kind='country')
        hungary.static_url = ';'
        hungary.save()

        budapest = Region.objects.get(kind='locality')
        budapest.subdomain = True
        budapest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_auto_20170412_1855'),
    ]

    operations = [
        migrations.RunPython(create_initial_regions_for_nesto, migrations.RunPython.noop),
    ]
