# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_ad_iframe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='building_walls',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '\u043a\u0438\u0440\u043f\u0438\u0447\u043d\u044b\u0439'), (2, '\u043f\u0430\u043d\u0435\u043b\u044c\u043d\u044b\u0439'), (3, '\u043c\u043e\u043d\u043e\u043b\u0438\u0442\u043d\u044b\u0439'), (4, '\u0431\u043b\u043e\u0447\u043d\u044b\u0439'), (5, '\u0434\u0435\u0440\u0435\u0432\u044f\u043d\u043d\u044b\u0439'), (6, '\u0440\u0430\u043a\u0443\u0448\u043d\u044f\u043a'), (7, '\u0441\u0430\u043c\u0430\u043d')], null=True, verbose_name='\u0442\u0438\u043f \u0441\u0442\u0435\u043d'),
        ),
    ]
