# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_auto_20170607_1333'),
        ('newhome', '0007_aggregate_layout_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='newhome_layout',
        ),
    ]
