# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models


def set_region_plan_discount(apps, schema_editor):
    from ad.models import Region  # используются методы модели, apps.get_model() не подойдет

    ukraina = Region.objects.get(static_url=';')

    for province_slug, plan_discount in (
        ('chernigovskaya-oblast', 0.67),
        ('ivano-frankovskaya-oblast', 0.62),
        ('chernovitskaya-oblast', 0.62),
        ('respublika-kryim', 0.43),
        ('ternopolskaya-oblast', 0.43),
        ('volyinskaya-oblast', 0.43),
        ('zakarpatskaya-oblast', 0.43),
        ('donetskaya-oblast', 0.61),
        ('luganskaya-oblast', 0.71),
    ):

        # get_descendants() используется, так как у нас оказалось два Крыма, наш и не наш
        province = ukraina.get_descendants().get(kind='province', slug=province_slug)
        province.plan_discount = plan_discount
        province.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_remove_ad_newhome_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='plan_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='\u0441\u043a\u0438\u0434\u043a\u0430 \u043d\u0430 \u0442\u0430\u0440\u0438\u0444\u044b'),
        ),
        migrations.RunPython(set_region_plan_discount, migrations.RunPython.noop),
    ]
