# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_region_plan_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='description_main',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description_rent',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description_rent_daily',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description_sale',
        ),
    ]
