# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_searchcounter_is_ad_view_referred_by_lunua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='iframe_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 3D \u0442\u0443\u0440 \u0438\u043b\u0438 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
