# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0017_ad_vip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='vip',
        ),
    ]
