# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0018_remove_ad_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price_uah',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='\u0446\u0435\u043d\u0430 \u0432 \u0433\u0440\u0438\u0432\u043d\u0430\u0445'),
        ),
        migrations.AlterIndexTogether(
            name='ad',
            index_together=set([('region', 'property_type', 'rooms'), ('user', 'created'), ('vip_type', 'updated', 'basead_ptr'), ('region', 'has_photos')]),
        ),
        migrations.AlterIndexTogether(
            name='searchcounter',
            index_together=set([('date', 'deal_type', 'region')]),
        ),
    ]
