# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models

def sync_partition_indexes(apps, schema_editor):
    from ad.models import Ad     # это не катит: Ad = apps.get_model('ad', 'Ad')
    Ad.sync_partition_indexes()


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0019_auto_20171011_0616'),
    ]

    operations = [
        migrations.RunPython(sync_partition_indexes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '\u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'), (210, '\u043d\u0435\u0430\u043a\u0442\u0438\u0432\u043d\u043e'), (211, '\u0443\u0434\u0430\u043b\u0435\u043d\u043e')], db_index=True, default=210, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vip_type',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=0, verbose_name='\u0442\u0438\u043f VIP-\u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f'),
        ),
    ]
