# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='\u043f\u0440\u0438\u0447\u0438\u043d\u0430 \u0431\u0430\u043d\u0430, \u043a\u043e\u0442\u043e\u0440\u0443\u044e \u0432\u0438\u0434\u0438\u0442 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('expire_date', models.DateField(verbose_name='\u0431\u0430\u043d \u0438\u0441\u0442\u0435\u043a\u0430\u0435\u0442')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='\u044e\u0437\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u0431\u0430\u043d \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
                'verbose_name_plural': '\u0431\u0430\u043d\u044b \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0441\u043e\u0437\u0434\u0430\u043d\u043e')),
                ('old_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u0441\u0442\u0430\u0440\u044b\u0439 email')),
                ('new_email', models.EmailField(max_length=254, verbose_name='\u043d\u043e\u0432\u044b\u0439 email')),
                ('confirmation_key', models.CharField(max_length=40, verbose_name='\u043a\u043e\u0434 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('status', models.CharField(choices=[(b'inactive', '\u043d\u0435\u0430\u043a\u0442\u0438\u0432\u043d\u043e'), (b'confirmed', '\u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u043e'), (b'cancelled', '\u043e\u0442\u043c\u0435\u043d\u0435\u043d\u043e')], default=b'inactive', max_length=20, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435 email',
                'verbose_name_plural': '\u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f email',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('readed', models.BooleanField(default=False, verbose_name='\u043f\u0440\u043e\u0447\u0438\u0442\u0430\u043d\u043e')),
                ('link_clicked', models.BooleanField(default=False, verbose_name='\u043f\u0435\u0440\u0435\u0445\u043e\u0434 \u043f\u043e \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('subject', models.CharField(choices=[(b'details', '\u0425\u043e\u0447\u0443 \u0443\u0437\u043d\u0430\u0442\u044c \u043d\u0435\u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0434\u0435\u0442\u0430\u043b\u0438'), (b'counteroffer', '\u0425\u043e\u0447\u0443 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0438\u0442\u044c \u0434\u0440\u0443\u0433\u0443\u044e \u0446\u0435\u043d\u0443')], max_length=50, null=True, verbose_name='\u0442\u0435\u043c\u0430')),
                ('basead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to=settings.AUTH_USER_MODEL, verbose_name='\u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c')),
                ('hidden_for_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u0441\u043a\u0440\u044b\u0442\u044c \u043f\u0435\u0440\u0435\u043f\u0438\u0441\u043a\u0443 \u0434\u043b\u044f \u044e\u0437\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0435\u0435 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0435 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='MessageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_user_by_type', models.CharField(blank=True, choices=[(b'person', '\u0422\u043e\u043b\u044c\u043a\u043e \u0447\u0430\u0441\u0442\u043d\u044b\u0435 \u043b\u0438\u0446\u0430'), (b'agency', '\u0422\u043e\u043b\u044c\u043a\u043e \u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u0430')], max_length=20, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u0442\u0438\u043f\u0443')),
                ('filter_user_by_ads_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u043e\u0431\u044a\u044f\u0432. - \u043c\u0438\u043d.')),
                ('filter_user_by_ads_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u043e\u0431\u044a\u044f\u0432. - \u043c\u0430\u043a\u0441.')),
                ('filter_user_by_plan', models.CharField(blank=True, choices=[(b'w-plan', '\u0441 \u0442\u0430\u0440\u0438\u0444\u043e\u043c'), (b'w-money-wo-plan', '\u0441 \u0434\u0435\u043d\u044c\u0433\u0430\u043c\u0438, \u043d\u043e \u0431\u0435\u0437 \u0442\u0430\u0440\u0438\u0444\u0430'), (b'wo-ads-w-plan', '\u0431\u0435\u0437 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f, \u043d\u043e \u0441 \u0442\u0430\u0440\u0438\u0444\u043e\u043c'), (b'w-ads-wo-plan', '\u0441 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f, \u043d\u043e \u0431\u0435\u0437 \u0442\u0430\u0440\u0438\u0444\u0430'), (b'w-overlimit', '\u0441 \u043f\u0440\u0435\u0432\u044b\u0448\u0435\u043d\u0438\u0435\u043c \u043f\u043e \u0442\u0430\u0440\u0438\u0444\u0443'), (b'w-expired-plan', '\u0441 \u0438\u0441\u0442\u0435\u043a\u0448\u0438\u043c \u043f\u043b\u0430\u043d\u043e\u043c'), (b'w-plan-first-time', '\u0441 \u043f\u043b\u0430\u043d\u043e\u043c \u0432\u043f\u0435\u0440\u0432\u044b\u0435'), (b'wo-any', '\u0431\u0435\u0437 \u0434\u0435\u043d\u0435\u0433, \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439 \u0438 \u0443\u0441\u043b\u0443\u0433')], max_length=20, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u0442\u0430\u0440\u0438\u0444\u0430\u043c')),
                ('filter_user_by_email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e e-mail')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
                ('title', models.CharField(max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f')),
                ('status', models.CharField(choices=[(b'not_sent', '\u043d\u0435 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0430'), (b'in_progress', '\u0432\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f'), (b'done', '\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430')], default=b'not_sent', max_length=20, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='\u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043d\u044b\u0445 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439')),
                ('filter_user_by_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u0440\u0435\u0433\u0438\u043e\u043d\u0443')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0430 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439',
                'verbose_name_plural': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_user_by_type', models.CharField(blank=True, choices=[(b'person', '\u0422\u043e\u043b\u044c\u043a\u043e \u0447\u0430\u0441\u0442\u043d\u044b\u0435 \u043b\u0438\u0446\u0430'), (b'agency', '\u0422\u043e\u043b\u044c\u043a\u043e \u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u0430')], max_length=20, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u0442\u0438\u043f\u0443')),
                ('filter_user_by_ads_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u043e\u0431\u044a\u044f\u0432. - \u043c\u0438\u043d.')),
                ('filter_user_by_ads_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u043e\u0431\u044a\u044f\u0432. - \u043c\u0430\u043a\u0441.')),
                ('filter_user_by_plan', models.CharField(blank=True, choices=[(b'w-plan', '\u0441 \u0442\u0430\u0440\u0438\u0444\u043e\u043c'), (b'w-money-wo-plan', '\u0441 \u0434\u0435\u043d\u044c\u0433\u0430\u043c\u0438, \u043d\u043e \u0431\u0435\u0437 \u0442\u0430\u0440\u0438\u0444\u0430'), (b'wo-ads-w-plan', '\u0431\u0435\u0437 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f, \u043d\u043e \u0441 \u0442\u0430\u0440\u0438\u0444\u043e\u043c'), (b'w-ads-wo-plan', '\u0441 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f, \u043d\u043e \u0431\u0435\u0437 \u0442\u0430\u0440\u0438\u0444\u0430'), (b'w-overlimit', '\u0441 \u043f\u0440\u0435\u0432\u044b\u0448\u0435\u043d\u0438\u0435\u043c \u043f\u043e \u0442\u0430\u0440\u0438\u0444\u0443'), (b'w-expired-plan', '\u0441 \u0438\u0441\u0442\u0435\u043a\u0448\u0438\u043c \u043f\u043b\u0430\u043d\u043e\u043c'), (b'w-plan-first-time', '\u0441 \u043f\u043b\u0430\u043d\u043e\u043c \u0432\u043f\u0435\u0440\u0432\u044b\u0435'), (b'wo-any', '\u0431\u0435\u0437 \u0434\u0435\u043d\u0435\u0433, \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439 \u0438 \u0443\u0441\u043b\u0443\u0433')], max_length=20, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u0442\u0430\u0440\u0438\u0444\u0430\u043c')),
                ('filter_user_by_email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e e-mail')),
                ('name', models.CharField(help_text='\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435', max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('text', models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('text_ru', models.TextField(null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('text_uk', models.TextField(null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('text_hu', models.TextField(null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='\u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435')),
                ('link_clicks', models.PositiveIntegerField(default=0, verbose_name='\u043a\u043b\u0438\u043a\u0438 \u043f\u043e \u0441\u0441\u044b\u043b\u043a\u0430\u043c')),
                ('filter_user_by_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u043f\u043e \u0440\u0435\u0433\u0438\u043e\u043d\u0443')),
            ],
            options={
                'verbose_name': '\u043d\u0430\u0441\u0442\u0440\u0430\u0438\u0432\u0430\u0435\u043c\u043e\u0435 \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u043d\u0430\u0441\u0442\u0440\u0430\u0438\u0432\u0430\u0435\u043c\u044b\u0435 \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='SavedAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('basead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ads', to='ad.BaseAd', verbose_name='\u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ads', to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'verbose_name': '\u0441\u043e\u0445\u0440. \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0441\u043e\u0445\u0440. \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[(b'rent', '\u0430\u0440\u0435\u043d\u0434\u0430'), (b'rent_daily', '\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0430\u0440\u0435\u043d\u0434\u0430'), (b'sale', '\u043f\u0440\u043e\u0434\u0430\u0436\u0430')], db_index=True, max_length=20, verbose_name='\u0442\u0438\u043f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('property_type', models.CharField(choices=[(b'flat', '\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), (b'room', '\u043a\u043e\u043c\u043d\u0430\u0442\u0430'), (b'house', '\u0434\u043e\u043c'), (b'plot', '\u0443\u0447\u0430\u0441\u0442\u043e\u043a'), (b'commercial', '\u043a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0430\u044f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c'), (b'garages', '\u0433\u0430\u0440\u0430\u0436\u0438')], db_index=True, max_length=20, null=True, verbose_name='\u0442\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('query', models.TextField(blank=True, null=True, verbose_name='\u043f\u043e\u0438\u0441\u043a\u043e\u0432\u044b\u0439 \u0437\u0430\u043f\u0440\u043e\u0441')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('subscribe', models.BooleanField(default=False, verbose_name='\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 ')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0433\u043e\u0440\u043e\u0434')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'verbose_name': '\u0441\u043e\u0445\u0440. \u043f\u043e\u0438\u0441\u043a',
                'verbose_name_plural': '\u0441\u043e\u0445\u0440. \u043f\u043e\u0438\u0441\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='\u043f\u0435\u0440\u0438\u043e\u0434')),
                ('new_properties', models.PositiveIntegerField(default=0, verbose_name='\u043d\u043e\u0432\u044b\u0445 \u043e\u0431\u044a\u044f\u0432.')),
                ('active_properties', models.PositiveIntegerField(default=0, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0445 \u043e\u0431\u044a\u044f\u0432.')),
                ('paid_properties', models.PositiveIntegerField(default=0, verbose_name='VIP-\u0440\u0430\u0437\u043c\u0435\u0449.')),
                ('money_spent', models.PositiveIntegerField(default=0, verbose_name='\u043f\u043e\u0442\u0440\u0430\u0447\u0435\u043d\u043e \u0433\u0440\u0438\u0432\u0435\u043d')),
                ('entrances', models.PositiveIntegerField(default=0, verbose_name='\u0432\u0445\u043e\u0434\u043e\u0432 \u043d\u0430 \u0441\u0430\u0439\u0442')),
                ('ad_views', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439')),
                ('ad_contacts_views', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043e\u0432')),
                ('plan_first', models.PositiveIntegerField(default=0, verbose_name='\u043f\u043b\u0430\u043d \u041f\u0435\u0440\u0432\u044b\u0439')),
                ('plan_other', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0447\u0438\u0435 \u043f\u043b\u0430\u043d\u044b')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u0437\u0430 \u0441\u0443\u0442\u043a\u0438',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439 \u0437\u0430 \u0441\u0443\u0442\u043a\u0438'
            },
        ),
        migrations.CreateModel(
            name='StatGrouped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='\u043f\u0435\u0440\u0438\u043e\u0434')),
                ('new_properties', models.PositiveIntegerField(default=0, verbose_name='\u043d\u043e\u0432\u044b\u0445 \u043e\u0431\u044a\u044f\u0432.')),
                ('active_properties', models.PositiveIntegerField(default=0, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0445 \u043e\u0431\u044a\u044f\u0432.')),
                ('paid_properties', models.PositiveIntegerField(default=0, verbose_name='VIP-\u0440\u0430\u0437\u043c\u0435\u0449.')),
                ('money_spent', models.PositiveIntegerField(default=0, verbose_name='\u043f\u043e\u0442\u0440\u0430\u0447\u0435\u043d\u043e \u0433\u0440\u0438\u0432\u0435\u043d')),
                ('entrances', models.PositiveIntegerField(default=0, verbose_name='\u0432\u0445\u043e\u0434\u043e\u0432 \u043d\u0430 \u0441\u0430\u0439\u0442')),
                ('ad_views', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439')),
                ('ad_contacts_views', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043e\u0432')),
                ('plan_first', models.PositiveIntegerField(default=0, verbose_name='\u043f\u043b\u0430\u043d \u041f\u0435\u0440\u0432\u044b\u0439')),
                ('plan_other', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0447\u0438\u0435 \u043f\u043b\u0430\u043d\u044b')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': '\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043f\u043e \u043f\u0435\u0440\u0438\u043e\u0434\u0430\u043c',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439 \u043f\u043e \u043f\u0435\u0440\u0438\u043e\u0434\u0430\u043c',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='message_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profile.MessageList', verbose_name='\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='message',
            name='root_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Message', verbose_name='\u043f\u0435\u0440\u0432\u043e\u0435 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u0433\u0440\u0443\u043f\u043f\u0438\u0440\u043a\u0438 \u0432 \u0434\u0438\u0430\u043b\u043e\u0433'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterUniqueTogether(
            name='statgrouped',
            unique_together=set([('date', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('date', 'user')]),
        ),
    ]
