# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_notification_show_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelist',
            name='filter_user_active_for_last_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0444\u0438\u043b\u044c\u0442\u0440 \u044e\u0437\u0435\u0440\u043e\u0432 \u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0445 \u0437\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 \u0425 \u043c\u0435\u0441\u044f\u0446\u0435\u0432'),
        ),
    ]
