# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 23:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


def create_managers(apps, schema_editor):
    Manager = apps.get_model('profile', 'Manager')
    User = apps.get_model('custom_user', 'User')

    users_in_field_manager = set(User.objects.filter(
        id__in=User.objects.filter(manager__isnull=False).values('manager')
    ))
    users_with_group = set(User.objects.filter(groups=2))

    for user in users_in_field_manager | users_with_group:
        print user.email
        m = Manager(user_ptr=user)
        m.__dict__.update(user.__dict__)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_django_110_alter_username'),
        ('profile', '0005_auto_20170317_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='manager_ptr', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('internal_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('image_big', models.ImageField(blank=True, null=True, upload_to=b'upload/manager', verbose_name='\u0431\u043e\u043b\u044c\u0448\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to=b'upload/manager', verbose_name='\u043c\u0430\u043b\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440',
                'verbose_name_plural': '\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440\u044b',
            },
            bases=('custom_user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(create_managers, migrations.RunPython.noop),
    ]
