# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 19:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


def update_savedsearches_parameters(apps, schema_editor):
    from ad.forms import PropertySearchForm

    import json
    import datetime

    multiple_fields = PropertySearchForm.get_multiple_fields()

    SavedSearch = apps.get_model('profile', 'SavedSearch')

    SavedSearch.objects.filter(created__lt=datetime.datetime(2015, 1, 1)).delete()

    for search in SavedSearch.objects.all():
        search.parameters = {
            'deal_type': search.deal_type,
            'property_type': search.property_type,
            'region': search.region.id,
        }
        if search.query:
            for name, value in json.loads(search.query).items():
                if (
                    name in ['region_id', 'deal_type', 'property_type', 'ordering'] or
                    (name == 'currency' and value == 'UAH')
                ):
                    continue
                else:
                    if name in multiple_fields and not isinstance(value, list):
                        search.parameters[name] = [value]
                    else:
                        search.parameters[name] = value

        search.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_manager_is_available_for_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='parameters',
            field=jsonfield.fields.JSONField(default=dict, null=True, verbose_name='\u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b'),
        ),
        migrations.RunPython(update_savedsearches_parameters, migrations.RunPython.noop),
    ]
