# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 19:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_savedsearch_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='deal_type',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='query',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='region',
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='parameters',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='\u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b'),
        ),
    ]
