# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_django_110_alter_username'),
        ('profile', '0006_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440, \u0437\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u0432\u0448\u0438\u0439 \u044d\u0442\u043e\u0433\u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_users', to='profile.Manager', verbose_name='\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440'),
        ),
    ]
