# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 20:21
from __future__ import unicode_literals

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[(b'ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), (b'uk', '\u0423\u043a\u0440\u0430\u0438\u043d\u0441\u043a\u0438\u0439'), (b'hu', '\u0412\u0435\u043d\u0433\u0435\u0440\u0441\u043a\u0438\u0439')], default=custom_user.models.get_default_language, max_length=2, verbose_name='\u044f\u0437\u044b\u043a'),
        ),
    ]
