# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_auto_20170616_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spcrm_category',
            field=models.CharField(blank=True, choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D')], max_length=1, null=True, verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0432 SalesPlatform CRM'),
        ),
    ]
