# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_user_spcrm_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u043f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loyalty_started',
            field=models.DateField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b \u043b\u043e\u044f\u043b\u044c\u043d\u043e\u0441\u0442\u0438'),
        ),
    ]
