# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import datetime
import dirtyfields.dirtyfields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ppc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0002_auto_20161229_0023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('paid_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsteriskLeadNumber',
            fields=[
                ('number', models.CharField(help_text='\u0444\u043e\u0440\u043c\u0430\u0442 \u0431\u0435\u0437 +380, \u0442.\u0435. 443376001', max_length=12, primary_key=True, serialize=False, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0410\u0422\u0421')),
                ('dstnumber1', models.CharField(help_text='\u0444\u043e\u0440\u043c\u0430\u0442 \u0431\u0435\u0437 +38, \u0442.\u0435. 0443376001', max_length=12, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043a\u043b\u0438\u0435\u043d\u0442\u0430 1')),
                ('dstnumber2', models.CharField(max_length=12, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043a\u043b\u0438\u0435\u043d\u0442\u0430 2')),
                ('dstnumber3', models.CharField(max_length=12, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043a\u043b\u0438\u0435\u043d\u0442\u0430 3')),
                ('mon', models.CharField(max_length=12, verbose_name='\u043f\u043d')),
                ('tue', models.CharField(max_length=12, verbose_name='\u0432\u0442')),
                ('wed', models.CharField(max_length=12, verbose_name='\u0441\u0440')),
                ('thu', models.CharField(max_length=12, verbose_name='\u0447\u0442')),
                ('fri', models.CharField(max_length=12, verbose_name='\u043f\u0442')),
                ('sat', models.CharField(max_length=12, verbose_name='\u0441\u0431')),
                ('sun', models.CharField(max_length=12, verbose_name='\u0432\u0441')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0430\u0432\u0438\u043b\u043e \u043f\u0435\u0440\u0435\u0430\u0434\u0440\u0435\u0430\u0446\u0438\u0438 \u0438 \u0432\u0440\u0435\u043c\u044f \u0440\u0430\u0431\u043e\u0442\u044b',
                'db_table': 'lead_numbers',
                'managed': False,
                'verbose_name_plural': '\u043f\u0440\u0430\u0432\u0438\u043b\u0430 \u043f\u0435\u0440\u0435\u0430\u0434\u0440\u0435\u0430\u0446\u0438\u0438 \u0438 \u0432\u0440\u0435\u043c\u044f \u0440\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[(b'ads', '\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'), (b'newhomes', '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438')], default=b'ads', max_length=15, verbose_name='\u0442\u0438\u043f \u043b\u0438\u0434\u043e\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='\u043e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435')),
                ('calls', models.PositiveIntegerField(default=0, verbose_name='\u0437\u0432\u043e\u043d\u043a\u043e\u0432')),
                ('requests', models.PositiveIntegerField(default=0, verbose_name='\u0437\u0432\u043e\u043d\u043a\u043e\u0432')),
                ('numbers', models.PositiveIntegerField(default=0, verbose_name='\u043d\u043e\u043c\u0435\u0440\u043e\u0432')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityperiods', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043f\u0435\u0440\u0438\u043e\u0434 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438 \u041f\u041f\u041a',
                'verbose_name_plural': '\u043f\u0435\u0440\u0438\u043e\u0434\u044b \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438 \u041f\u041f\u041a',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e')),
                ('end', models.DateTimeField(blank=True, help_text='\u0434\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0432\u044b\u0441\u0442\u0430\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u043f\u043e\u0441\u043b\u0435 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f 10 \u0437\u0432\u043e\u043d\u043a\u043e\u0432/\u043b\u0438\u0434\u043e\u0432', null=True, verbose_name='\u043a\u043e\u043d\u0435\u0446')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadgenerationbonuses', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0431\u043e\u043d\u0443\u0441\u044b \u043f\u043e \u043b\u0438\u0434\u0435\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u0431\u043e\u043d\u0443\u0441\u044b \u043f\u043e \u043b\u0438\u0434\u0435\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(db_index=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0437\u0432\u043e\u043d\u043a\u0430')),
                ('answer_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u0442\u0432\u0435\u0442\u0430 \u043d\u0430 \u0437\u0432\u043e\u043d\u043e\u043a')),
                ('hang_up_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435 \u0437\u0432\u043e\u043d\u043a\u0430')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0440\u0430\u0437\u0433\u043e\u0432\u043e\u0440\u0430')),
                ('callerid1', models.CharField(default=b'', max_length=14, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0437\u0432\u043e\u043d\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('uniqueid1', models.CharField(db_index=True, default=b'', max_length=40, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0432\u043e\u043d\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('callerid2', models.CharField(blank=True, default=b'', max_length=14, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043e\u0442\u0432\u0435\u0442\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('uniqueid2', models.CharField(blank=True, db_index=True, default=b'', max_length=40, verbose_name='\u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043e\u0442\u0432\u0435\u0442\u0438\u0432\u0448\u0435\u0433\u043e')),
                ('deal_type', models.CharField(blank=True, choices=[(b'rent', '\u0430\u0440\u0435\u043d\u0434\u0430'), (b'rent_daily', '\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0430\u0440\u0435\u043d\u0434\u0430'), (b'sale', '\u043f\u0440\u043e\u0434\u0430\u0436\u0430'), (b'newhomes', '\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438')], max_length=15, verbose_name='\u0442\u0438\u043f \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
                ('complaint', models.CharField(blank=True, choices=[(b'awaiting', '\u0440\u0430\u0441\u0441\u043c\u0430\u0442\u0438\u0432\u0430\u0435\u0442\u0441\u044f'), (b'rejected', '\u043e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u0430'), (b'accepted', '\u043f\u0440\u0438\u043d\u044f\u0442\u0430')], max_length=10, null=True, verbose_name='\u0436\u0430\u043b\u043e\u0431\u0430')),
                ('recordingfile', models.FileField(blank=True, null=True, upload_to=ppc.models.make_call_upload_path, verbose_name='\u0437\u0430\u043f\u0438\u0441\u044c \u0440\u0430\u0437\u0433\u043e\u0432\u043e\u0440\u0430')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paidcalls', to='paid_services.Transaction', verbose_name='\u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_ppc_calls', to=settings.AUTH_USER_MODEL, verbose_name='\u0437\u0432\u043e\u043d\u0438\u0432\u0448\u0438\u0439 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_ppc_calls', to=settings.AUTH_USER_MODEL, verbose_name='\u043e\u0442\u0432\u0435\u0442\u0438\u0432\u0448\u0438\u0439 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043f\u043b\u0430\u0442\u043d\u044b\u0439 \u0437\u0432\u043e\u043d\u043e\u043a',
                'verbose_name_plural': '\u043f\u043b\u0430\u0442\u043d\u044b\u0435 \u0437\u0432\u043e\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol=b'IPv4', verbose_name='IP \u0430\u0434\u0440\u0435\u0441 \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0438\u043c\u044f')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('referer', models.URLField(blank=True, max_length=512, verbose_name=b'\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 \xd0\xbe\xd0\xb1\xd1\x8a\xd0\xb5\xd0\xba\xd1\x82\xd0\xb0')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paidcallrequests', to='paid_services.Transaction', verbose_name='\u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('user1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callrequests_from', to=settings.AUTH_USER_MODEL, verbose_name='\u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('user2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callrequests_to', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c \u0437\u0430\u044f\u0432\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u043e\u0431\u0440\u0430\u0442\u043d\u044b\u0439 \u0437\u0432\u043e\u043d\u043e\u043a',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043e\u0431\u0440\u0430\u0442\u043d\u044b\u0439 \u0437\u0432\u043e\u043d\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='LeadGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_ads', models.BooleanField(default=False, verbose_name='\u0432\u043a\u043b\u044e\u0447\u0435\u043d\u043e \u0434\u043b\u044f \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439')),
                ('is_active_newhomes', models.BooleanField(default=False, verbose_name='\u0432\u043a\u043b\u044e\u0447\u0435\u043d\u043e \u0434\u043b\u044f \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0435\u043a')),
                ('ads_limit', models.PositiveIntegerField(default=40, verbose_name='\u043b\u0438\u043c\u0438\u0442 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439 \u043f\u043e \u041f\u041f\u041a')),
                ('worktime', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(blank=True, default=datetime.timedelta), size=2), blank=True, null=True, size=7, verbose_name='\u0440\u0430\u0431\u043e\u0447\u0438\u0435 \u0434\u043d\u0438')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043b\u0438\u0434\u043e\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043b\u0438\u0434\u043e\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProxyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043a\u043e\u043b-\u0446\u0435\u043d\u0442\u0440\u0430')),
                ('deal_type', models.CharField(blank=True, choices=[(b'rent', '\u0430\u0440\u0435\u043d\u0434\u0430'), (b'rent_daily', '\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0430\u0440\u0435\u043d\u0434\u0430'), (b'sale', '\u043f\u0440\u043e\u0434\u0430\u0436\u0430'), (b'newhomes', '\u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438')], max_length=15, null=True, verbose_name='\u0442\u0438\u043f \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('hold_until', models.DateTimeField(blank=True, help_text='\u0434\u043e \u043a\u0430\u043a\u043e\u0433\u043e \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u044d\u0442\u043e\u0442 \u043d\u043e\u043c\u0435\u0440 \u0431\u0443\u0434\u0435\u0442 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u0435\u043d \u0434\u043b\u044f \u0432\u044b\u0434\u0430\u0447\u0438 \u043d\u043e\u0432\u044b\u043c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f\u043c', null=True, verbose_name='\u0437\u0430\u043d\u044f\u0442 \u0434\u043e')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0440\u0435\u0433\u0438\u043e\u043d')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxynumbers', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043d\u043e\u043c\u0435\u0440 \u0434\u043b\u044f \u043b\u0438\u0434\u043e\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u043d\u043e\u043c\u0435\u0440\u0430 \u0434\u043b\u044f \u043b\u0438\u0434\u043e\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438',
            },
        ),
    ]
