# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 03:24
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ProxyNumber = apps.get_model("ppc", "ProxyNumber")
    LeadGeneration = apps.get_model("ppc", "LeadGeneration")
    ActivityPeriod = apps.get_model("ppc", "ActivityPeriod")

    ProxyNumber.objects.bulk_create([
        ProxyNumber(number="380673262813", provider="ringostat", is_shared=True),
        ProxyNumber(number="380673262814", provider="ringostat", is_shared=True),
        ProxyNumber(number="380673262815", provider="ringostat", is_shared=True),
        ProxyNumber(number="380673262816", provider="ringostat", is_shared=True),
        ProxyNumber(number="380673262817", provider="ringostat", is_shared=True),
        ProxyNumber(number="380673262818", provider="ringostat", is_shared=True),
        ProxyNumber(number="380673262819", provider="ringostat", is_shared=True, deal_type="newhomes"),
        ProxyNumber(number="380673262821", provider="ringostat"),
        ProxyNumber(number="380673262822", provider="ringostat"),
        ProxyNumber(number="380673262823", provider="ringostat"),
        ProxyNumber(number="380673262824", provider="ringostat"),
        ProxyNumber(number="380673262825", provider="ringostat"),
        ProxyNumber(number="380673262826", provider="ringostat"),
        ProxyNumber(number="380673262830", provider="ringostat"),
        ProxyNumber(number="380673262831", provider="ringostat"),
        ProxyNumber(number="380673262832", provider="ringostat"),
        ProxyNumber(number="380673262833", provider="ringostat"),
        ProxyNumber(number="380673262834", provider="ringostat"),
        ProxyNumber(number="380673262835", provider="ringostat"),
        ProxyNumber(number="380673262836", provider="ringostat")
    ])

    users_with_active_ppk = ActivityPeriod.objects.filter(end=None).values_list('user', flat=True)
    LeadGeneration.objects.exclude(user__in=users_with_active_ppk).update(use_old_numbers=False)


def reverse_func(apps, schema_editor):
    ProxyNumber = apps.get_model("ppc", "ProxyNumber")
    LeadGeneration = apps.get_model("ppc", "LeadGeneration")

    ProxyNumber.objects.filter(provider="ringostat").delete()
    LeadGeneration.objects.update(use_old_numbers=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0002_auto_20161229_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgeneration',
            name='use_old_numbers',
            field=models.BooleanField(default=False, verbose_name='\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442\u0441\u044f \u043d\u043e\u043c\u0435\u0440\u0430 \u043e\u0444\u0438\u0441\u043d\u043e\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0438\u0438'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
