# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0006_proxynumber_traffic_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgeneration',
            name='is_shown_users_phone',
            field=models.BooleanField(default=False, verbose_name='\u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0442\u0435\u043b\u0435\u0444\u043e\u043d \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
