# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0008_auto_20170306_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='proxynumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='ppc.ProxyNumber', verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043f\u0435\u0440\u0435\u0430\u0434\u0440\u0435\u0441\u0430\u0446\u0438\u0438'),
        ),
    ]
