# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0009_auto_20170314_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadgeneration',
            name='use_old_numbers',
        ),
        migrations.AddField(
            model_name='proxynumber',
            name='mobile_operator',
            field=models.CharField(blank=True, choices=[(b'kievstar', '\u041a\u0438\u0435\u0432\u0421\u0442\u0430\u0440'), (b'mts', '\u041c\u0422\u0421'), (b'life', '\u041b\u0430\u0439\u0444')], max_length=10, null=True, verbose_name='\u043e\u043f\u0435\u0440\u0430\u0442\u043e\u0440'),
        ),
    ]
