# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:27
from __future__ import unicode_literals

from django.db import migrations


new_numbers = {
    'life' : {
        '380637632415': 'yandex', '380637632450': 'google', '380637632456': 'trovit', '380637632467': 'mitula',
        '380931437831': 'lun', '380931437851': 'direct', '380931437858': 'seo', '380730922570': 'facebook',
        '380730922571': 'vk',
    },
    'mts': {'380952852798': 'yandex', '380952852869': 'google', '380952852895': 'trovit', '380952852896': 'mitula',
            '380503177423': 'lun', '380504736389': 'direct', '380504749355': 'seo', '380504973106': 'facebook',
            '380504973108': 'vk',
    }
}

def add_new_numbers(apps, schema_editor):
    ProxyNumber = apps.get_model("ppc", "ProxyNumber")
    ProxyNumber.objects.filter(provider='ringostat', mobile_operator=None).update(mobile_operator='kievstar')

    for operator, numbers in new_numbers.items():
        for number, traffic_source in numbers.items():
            print ProxyNumber.objects.get_or_create(number=number, defaults={'provider':'ringostat', 'traffic_source':traffic_source, 'is_shared':True, 'mobile_operator':operator})

def remove_new_numbers(apps, schema_editor):
    ProxyNumber = apps.get_model("ppc", "ProxyNumber")
    for operator, numbers in new_numbers.items():
        for number, traffic_source in numbers.items():
            ProxyNumber.objects.filter(number=number).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0010_auto_20170414_1726'),
    ]

    operations = [
        migrations.RunPython(add_new_numbers, remove_new_numbers),
    ]
