# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0011_add_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='traffic_source',
            field=models.CharField(blank=True, choices=[(b'direct', '\u043f\u0440\u044f\u043c\u044b\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u044b'), (b'yandex-cpc', '\u044f\u043d\u0434\u0435\u043a\u0441 \u0434\u0438\u0440\u0435\u043a\u0442'), (b'google-cpc', 'adwords'), (b'other', '\u0434\u0440\u0443\u0433\u043e\u0435'), (b'seo', '\u043f\u043e\u0438\u0441\u043a\u043e\u0432\u044b\u0435 \u0441\u0438\u0441\u0442\u0435\u043c\u044b'), (b'lun', b'lun.ua'), (b'trovit', b'trovit'), (b'mitula', b'mitula'), (b'facebook', b'facebook'), (b'vk.com', '\u0432\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435')], max_length=10, verbose_name='\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0442\u0440\u0430\u0444\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='proxynumber',
            name='traffic_source',
            field=models.CharField(blank=True, choices=[(b'direct', '\u043f\u0440\u044f\u043c\u044b\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u044b'), (b'yandex-cpc', '\u044f\u043d\u0434\u0435\u043a\u0441 \u0434\u0438\u0440\u0435\u043a\u0442'), (b'google-cpc', 'adwords'), (b'other', '\u0434\u0440\u0443\u0433\u043e\u0435'), (b'seo', '\u043f\u043e\u0438\u0441\u043a\u043e\u0432\u044b\u0435 \u0441\u0438\u0441\u0442\u0435\u043c\u044b'), (b'lun', b'lun.ua'), (b'trovit', b'trovit'), (b'mitula', b'mitula'), (b'facebook', b'facebook'), (b'vk.com', '\u0432\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435')], max_length=10, verbose_name='\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0442\u0440\u0430\u0444\u0438\u043a\u0430'),
        ),
    ]
