# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_nesto_initial_regions'),
        ('ppc', '0012_auto_20170523_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('detail_views', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('traffic_source', models.CharField(choices=[(b'direct', '\u043f\u0440\u044f\u043c\u044b\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u044b'), (b'yandex-cpc', '\u044f\u043d\u0434\u0435\u043a\u0441 \u0434\u0438\u0440\u0435\u043a\u0442'), (b'google-cpc', 'adwords'), (b'other', '\u0434\u0440\u0443\u0433\u043e\u0435'), (b'seo', '\u043f\u043e\u0438\u0441\u043a\u043e\u0432\u044b\u0435 \u0441\u0438\u0441\u0442\u0435\u043c\u044b'), (b'lun', b'lun.ua'), (b'trovit', b'trovit'), (b'mitula', b'mitula'), (b'facebook', b'facebook'), (b'vk.com', '\u0432\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435')], max_length=10, verbose_name='\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0442\u0440\u0430\u0444\u0438\u043a\u0430')),
                ('basead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc_viewscounts', to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f c \u041f\u041f\u041a',
                'verbose_name_plural': '\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439 \u0441 \u041f\u041f\u041a',
            },
        ),
    ]
