# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import ppc.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0013_viewscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0438\u043c\u044f')),
                ('company', models.CharField(max_length=50, verbose_name='\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f')),
                ('text', models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442 \u043e\u0442\u0437\u044b\u0432\u0430')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ppc.models.make_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u043e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u043e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
    ]
