# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('until', models.DateTimeField(verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u043e?')),
                ('catalog', models.CharField(choices=[(b'intl_mesto', '\u0437\u0430\u0440\u0443\u0431\u0435\u0436\u043d\u0430\u044f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c mesto.ua'), (b'worldwide', '\u0437\u0430\u0440\u0443\u0431\u0435\u0436\u043d\u044b\u0435 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0438')], max_length=30, verbose_name='\u043a\u0430\u0442\u0430\u043b\u043e\u0433 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('basead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogplacements', to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u0435 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430\u0445',
                'verbose_name_plural': '\u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430\u0445',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f')),
                ('services', models.TextField(verbose_name='\u0443\u0441\u043b\u0443\u0433\u0438')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0441\u0443\u043c\u043c\u0430, \u0433\u0440\u043d')),
                ('is_paid', models.BooleanField(default=False, verbose_name='\u043e\u043f\u043b\u0430\u0447\u0435\u043d?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0437\u0430\u043a\u0430\u0437\u044b',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_hu', models.CharField(max_length=50, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('ads_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u043b\u0438\u043c\u0438\u0442 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439')),
                ('update_interval', models.PositiveIntegerField(choices=[(3, 3), (7, 7)], verbose_name='\u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f, \u0434\u043d\u0435\u0439')),
                ('duration', models.PositiveIntegerField(default=31, verbose_name='\u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c, \u0434\u043d\u0435\u0439')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='\u0431\u043e\u043d\u0443\u0441\u043d\u044b\u0439?')),
                ('is_popular', models.BooleanField(default=False, verbose_name='\u043f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0439?')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u0434\u0435\u0439\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0439?')),
            ],
            options={
                'verbose_name': '\u0442\u0430\u0440\u0438\u0444',
                'verbose_name_plural': '\u0442\u0430\u0440\u0438\u0444\u044b',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, '\u043f\u043e\u043f\u043e\u043b\u043d: \u0431\u043e\u043d\u0443\u0441'), (2, '\u043f\u043e\u043f\u043e\u043b\u043d: \u043f\u043b\u0430\u0442\u0435\u0436\u043d\u0430\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u0430'), (31, '\u0432\u043e\u0437\u0432\u0440\u0430\u0442 \u043e\u0441\u0442\u0430\u0442\u043a\u0430 \u0437\u0430 \u043f\u0430\u043a\u0435\u0442 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0439'), (32, '\u0432\u043e\u0437\u0432\u0440\u0430\u0442 \u043f\u0440\u0438 \u043e\u0442\u043c\u0435\u043d\u0435 \u0442\u0430\u0440\u0438\u0444\u0430'), (33, '\u0432\u043e\u0437\u0432\u0440\u0430\u0442 \u043e\u0441\u0442\u0430\u0442\u043a\u0430 \u043f\u0440\u0438 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0435 \u0442\u0430\u0440\u0438\u0444\u0430'), (4, '\u043f\u043e\u043f\u043e\u043b\u043d: \u043d\u043e\u0432\u043e\u0433\u043e\u0434\u043d\u044f\u044f \u0430\u043a\u0446\u0438\u044f'), (5, '\u043f\u043e\u043f\u043e\u043b\u043d: \u0447\u0435\u0440\u0435\u0437 \u043f\u0440\u043e\u043c\u043e-\u043a\u043e\u0434'), (6, '\u043f\u043e\u043f\u043e\u043b\u043d: \u0431\u043e\u043d\u0443\u0441 \u043f\u0440\u0438 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438'), (7, '\u043f\u043e\u043f\u043e\u043b\u043d: \u0441\u0447\u0435\u0442-\u0444\u0430\u043a\u0442\u0443\u0440\u0430'), (9, '\u043f\u043e\u043f\u043e\u043b\u043d: \u0431\u043e\u043d\u0443\u0441 \u0441 \u0422\u0412 \u0440\u0435\u043a\u043b\u0430\u043c\u044b'), (8, '\u043f\u0435\u0440\u0435\u0432\u043e\u0434: \u043a \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044e'), (21, '\u043f\u0435\u0440\u0435\u0432\u043e\u0434: \u043e\u0442 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'), (11, '\u0442\u0430\u0440\u0438\u0444: \u043f\u043e\u043a\u0443\u043f\u043a\u0430'), (12, '\u0442\u0430\u0440\u0438\u0444: \u0443\u043b\u0443\u0447\u0448\u0435\u043d\u0438\u0435'), (51, '\u043e\u043f\u043b\u0430\u0442\u0430 \u043f\u0440\u0435\u043c\u0438\u0443\u043c \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'), (52, '\u043e\u043f\u043b\u0430\u0442\u0430 \u044d\u043a\u0441\u043a\u043b\u044e\u0437\u0438\u0432\u043d\u043e\u0433\u043e \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'), (53, '\u0440\u0430\u0437\u043c\u0435\u0449: VIP'), (54, '\u0440\u0430\u0437\u043c\u0435\u0449: \u0437\u0430\u0440\u0443\u0431\u0435\u0436 mesto.ua'), (55, '\u0440\u0430\u0437\u043c\u0435\u0449: \u0437\u0430\u0440\u0443\u0431\u0435\u0436 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b'), (3, '\u0440\u0430\u0437\u043c\u0435\u0449: \u0432\u043e\u0437\u0432\u0440\u0430\u0442'), (61, '\u043e\u043f\u043b\u0430\u0442\u0430 \u0441\u0447\u0435\u0442\u0430 \u043f\u043e \u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e\u0439 \u0430\u0440\u0435\u043d\u0434\u0435'), (71, '\u043e\u043f\u043b\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439'), (81, '\u043e\u043f\u043b\u0430\u0442\u0430 \u043f\u0440\u043e\u0434\u043b\u0435\u043d\u0438\u044f CRM'), (82, '\u043f\u043f\u043a: \u043b\u0438\u0434 (\u0443\u0441\u0442\u0430\u0440\u0435\u0432\u0448)'), (83, '\u043f\u043f\u043a: \u0437\u0430\u043a\u0430\u0437'), (84, '\u043f\u043f\u043a: \u0437\u0432\u043e\u043d\u043e\u043a'), (85, '\u043f\u043f\u043a: \u0437\u0432\u043e\u043d\u043e\u043a \u043f\u0440\u043e\u043f\u0443\u0449'), (34, '\u043f\u043f\u043a: \u0432\u043e\u0437\u0432\u0440\u0430\u0442 \u0437\u0430 \u0437\u0432\u043e\u043d\u043e\u043a'), (91, '\u043e\u043f\u043b\u0430\u0442\u0430 \u043f\u0430\u043a\u0435\u0442\u043d\u043e\u0433\u043e \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'), (92, '\u043e\u043f\u043b\u0430\u0442\u0430 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u043e\u0433\u043e \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')], db_index=True, default=0, verbose_name='\u0442\u0438\u043f')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0441\u0443\u043c\u043c\u0430 \u0433\u0440\u043d')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='\u0437\u0430\u043c\u0435\u0442\u043a\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('lottery_is_required', models.BooleanField(default=False, verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u043d\u043e\u0432\u043e\u0433\u043e\u0434\u043d\u0435\u0439 \u0430\u043a\u0446\u0438\u0438')),
                ('lottery_percent', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043d\u0430\u0447\u0438\u0441\u043b\u0435\u043d\u0438\u044f')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paid_services.Order', verbose_name='\u0437\u0430\u043a\u0430\u0437')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ['-time'],
                'verbose_name': '\u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u043b\u0438\u043c\u0438\u0442 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='\u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u043e?')),
                ('not_affect_to_discount', models.BooleanField(default=False, verbose_name='\u043d\u0435 \u0443\u0447\u0438\u0442\u044b\u0432\u0430\u0442\u044c \u043f\u0440\u0438 \u0440\u0430\u0441\u0447\u0435\u0442\u0435 \u0441\u043a\u0438\u0434\u043a\u0438')),
                ('bonus2016', models.BooleanField(default=False, verbose_name='\u0431\u043e\u043d\u0443\u0441\u043d\u044b\u0439 2\u0445 \u043d\u0435\u0434\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u0430\u0440\u0438\u0444 \u043d\u0430 10 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='paid_services.Plan', verbose_name='\u0442\u0430\u0440\u0438\u0444')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0440\u0435\u0433\u0438\u043e\u043d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ['start'],
                'verbose_name': '\u0442\u0430\u0440\u0438\u0444 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u0442\u0430\u0440\u0438\u0444\u044b \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
                'permissions': (('cancel_userplan', '\u041e\u0442\u043c\u0435\u043d\u0430 \u0442\u0430\u0440\u0438\u0444\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),),
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='VipPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('until', models.DateTimeField(verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u043e?')),
                ('days', models.PositiveIntegerField(verbose_name='\u0441\u0440\u043e\u043a, \u0434\u043d\u0435\u0439')),
                ('basead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vipplacements', to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vipplacements', to='paid_services.Transaction', verbose_name='\u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b')),
            ],
            options={
                'verbose_name': 'VIP \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': 'VIP \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
                'permissions': (('cancel_vipplacement', '\u041e\u0442\u043c\u0435\u043d\u0430 VIP \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f'),),
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paid_services.UserPlan', verbose_name='\u0442\u0430\u0440\u0438\u0444 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='catalogplacement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogplacements', to='paid_services.Transaction', verbose_name='\u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
