# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0002_auto_20161229_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='\u043d\u0430\u043f\u043e\u043c\u0438\u043d\u0430\u043d\u0438\u0435 \u043e \u043d\u0435\u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043d\u043e\u043c \u0437\u0430\u043a\u0430\u0437\u0435 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e'),
        ),
    ]
