# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0003_order_is_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_bonus',
        ),
    ]
