# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0005_remove_lottery2017_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureMLLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', jsonfield.fields.JSONField()),
                ('scored_probabilities', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='azureml', to='paid_services.Transaction')),
            ],
        ),
    ]
