# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0006_azuremllogentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AzureMLLogEntry',
            new_name='AzureMLEntry',
        ),
    ]
