# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 17:04
from __future__ import unicode_literals

from django.db import migrations


def update_ads(apps, schema_editor):
    from paid_services.models import VipPlacement  # используются методы модели, apps.get_model() не подойдет
    from ad.models import Ad

    for ad in Ad.objects.filter(pk__in=VipPlacement.objects.values('basead')):
        ad.update_vip()


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0008_auto_20170922_0403'),
    ]

    operations = [
        migrations.RunPython(update_ads, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='catalogplacement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vipplacement',
            name='is_active',
        ),
    ]
