# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0009_remove_paidplacement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipplacement',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 1)], default=1, verbose_name='\u0442\u0438\u043f'),
        ),
    ]
