# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 02:37
from __future__ import unicode_literals
import re

from django.db import migrations

from paid_services.models import TRANSACTION_TYPE_CHOICES

def convert_transactions(apps, schema_editor):
    Transaction = apps.get_model('paid_services', 'Transaction')

    print
    old_trans_types = [type for type, label in TRANSACTION_TYPE_CHOICES if u'возврат' in label]
    p = re.compile(r'[.]*#(\d+)[.]*')
    for transaction in Transaction.objects.filter(type__in=old_trans_types):
        user = transaction.user
        if '#' in transaction.comment:
            object_id = p.search(transaction.comment).groups()[0]

        print transaction.type, ':  ', transaction.id, transaction.comment, transaction.amount, transaction.time
        if transaction.type == 3:
            corrected_transaction = user.transactions.filter(
                vipplacements=object_id).first() or user.transactions.filter(catalogplacements=object_id).first()
        elif transaction.type == 31:
            corrected_transaction = Transaction.objects.filter(comment__icontains='Оплата пакетного объявлений #%s' % object_id).first()
        elif transaction.type in [32, 33]:
            corrected_transaction = Transaction.objects.filter(type=11, user_plan_id=object_id).first()
        elif transaction.type == 34:
            corrected_transaction = Transaction.objects.filter(type__in=[84, 85], note__icontains=transaction.note.replace(u'возврат за ', '')).first() # comment__contains='#%s' % object_id

        # print '  found', corrected_transaction.id, corrected_transaction.amount, corrected_transaction.comment
        transaction.corrected_transaction = corrected_transaction
        transaction.type = 100
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0012_auto_20171013_1446'),
    ]

    operations = [
        migrations.RunPython(convert_transactions, migrations.RunPython.noop),
    ]
