# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0004_auto_20170112_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAutoposting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438/\u0433\u0440\u0443\u043f\u043f\u044b')),
                ('page_id', models.CharField(max_length=255, verbose_name='ID \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432 Facebook')),
                ('deal_type', models.CharField(choices=[(b'rent', '\u0430\u0440\u0435\u043d\u0434\u0430'), (b'rent_daily', '\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0430\u0440\u0435\u043d\u0434\u0430'), (b'sale', '\u043f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=12, verbose_name='\u0422\u0438\u043f \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e?')),
                ('last_posting_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0439 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Long Term Access Token')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f \u0442\u043e\u043a\u0435\u043d\u0430')),
                ('language', models.CharField(choices=[(b'ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), (b'uk', '\u0423\u043a\u0440\u0430\u0438\u043d\u0441\u043a\u0438\u0439')], default='ru', max_length=2, verbose_name='\u044f\u0437\u044b\u043a')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0443',
                'verbose_name_plural': '\u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0430\u0432\u0442\u043e\u043f\u043e\u0441\u0442\u0438\u043d\u0433\u0430 \u0434\u043b\u044f Facebook',
            },
        ),
        migrations.CreateModel(
            name='FacebookAutopostingAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, verbose_name='Facebook page id')),
                ('basead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_autoposting_ads', to='ad.BaseAd')),
                ('facebook_autoposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoposting.FacebookAutoposting')),
            ],
        ),
    ]
