# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoposting', '0002_vkautoposting_vkautopostingad'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookautoposting',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u0446\u0435\u043d\u0430 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f, \u0433\u0440\u043d'),
        ),
    ]
