# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webinars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=webinars.models.make_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('order', models.IntegerField(default=0, help_text='\u0427\u0435\u043c \u043d\u0438\u0436\u0435 \u0447\u0438\u0441\u043b\u043e, \u0442\u0435\u043c \u0440\u0430\u043d\u044c\u0448\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0437\u0438\u0442\u0441\u044f \u0444\u043e\u0442\u043e', verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0444\u043e\u0442\u043e')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0424\u043e\u0442\u043e',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e \u0441 \u0441\u0435\u043c\u0438\u043d\u0430\u0440\u043e\u0432',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='SeminarVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(verbose_name='\u043a\u043e\u0434 \u0432\u0438\u0434\u0435\u043e')),
                ('order', models.IntegerField(default=0, help_text='\u0427\u0435\u043c \u043d\u0438\u0436\u0435 \u0447\u0438\u0441\u043b\u043e, \u0442\u0435\u043c \u0440\u0430\u043d\u044c\u0448\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0437\u0438\u0442\u0441\u044f \u0444\u043e\u0442\u043e', verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0432\u0438\u0434\u0435\u043e')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e \u0441 \u0441\u0435\u043c\u0438\u043d\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u0424\u0418\u041e \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('name_uk', models.CharField(max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('name_hu', models.CharField(max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('title', models.TextField(verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('title_ru', models.TextField(null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('title_uk', models.TextField(null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('title_hu', models.TextField(null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c \u0441\u043f\u0438\u043a\u0435\u0440\u0430')),
                ('image', models.ImageField(help_text='\u0412\u043d\u0438\u043c\u0430\u043d\u0438\u0435! \u0424\u043e\u0442\u043e \u043d\u0435 \u043f\u0435\u0440\u0435\u0436\u0438\u043c\u0430\u0435\u0442\u0441\u044f', upload_to=b'upload/speaker/', verbose_name='\u0424\u043e\u0442\u043e \u0441\u043f\u0438\u043a\u0435\u0440\u0430 (105x105)')),
            ],
            options={
                'verbose_name': '\u0412\u0435\u0434\u0443\u0449\u0438\u0439',
                'verbose_name_plural': '\u0412\u0435\u0434\u0443\u0449\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0438\u043c\u0432\u043e\u043b # \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u043d\u043e\u0441\u0430 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0438\u043c\u0432\u043e\u043b # \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u043d\u043e\u0441\u0430 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_uk', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0438\u043c\u0432\u043e\u043b # \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u043d\u043e\u0441\u0430 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_hu', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0438\u043c\u0432\u043e\u043b # \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u043d\u043e\u0441\u0430 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u0441\u0435\u043c\u0438\u043d\u0430\u0440\u0430')),
                ('city_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u0441\u0435\u043c\u0438\u043d\u0430\u0440\u0430')),
                ('city_uk', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u0441\u0435\u043c\u0438\u043d\u0430\u0440\u0430')),
                ('city_hu', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u0441\u0435\u043c\u0438\u043d\u0430\u0440\u0430')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='\u0447\u0430\u0441\u0442\u044c URL-\u0430')),
                ('video', models.CharField(blank=True, help_text='\u041f\u0440\u0438 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0438 \u043a\u043e\u0434\u0430 - \u0432\u0435\u0431\u0438\u043d\u0430\u0440 \u0441\u0447\u0438\u0442\u0430\u0435\u0442\u0441\u044f \u043d\u0430\u0447\u0430\u0432\u0448\u0438\u043c\u0441\u044f', max_length=255, null=True, verbose_name='\u041a\u043e\u0434 \u0432\u0441\u0442\u0430\u0432\u043a\u0438 \u043f\u043b\u0435\u0435\u0440\u0430')),
                ('type', models.CharField(choices=[(b'webinar', '\u0432\u0435\u0431\u0438\u043d\u0430\u0440'), (b'seminar', '\u0441\u0435\u043c\u0438\u043d\u0430\u0440')], default=b'webinar', max_length=10, verbose_name='\u0442\u0438\u043f \u0442\u0440\u0435\u043d\u0438\u043d\u0433\u0430')),
                ('is_published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d?')),
                ('is_registration_available', models.BooleanField(default=True, verbose_name='\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430?')),
                ('teaser', models.TextField(help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', verbose_name='\u041a\u0440\u0430\u0442\u043a\u0438\u0439 \u043e\u0431\u0437\u043e\u0440')),
                ('teaser_ru', models.TextField(help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u0438\u0439 \u043e\u0431\u0437\u043e\u0440')),
                ('teaser_uk', models.TextField(help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u0438\u0439 \u043e\u0431\u0437\u043e\u0440')),
                ('teaser_hu', models.TextField(help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u0438\u0439 \u043e\u0431\u0437\u043e\u0440')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430')),
                ('description_ru', models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430')),
                ('description_uk', models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430')),
                ('description_hu', models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430')),
                ('image', models.ImageField(blank=True, help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0432\u0435\u0431\u0438\u043d\u0430\u0440', null=True, upload_to=b'upload/webinar/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432 \u0448\u0430\u043f\u043a\u0443 (1200x260)')),
                ('youtube_image', models.CharField(blank=True, help_text='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u043e\u0432, \u0432 \u0430\u0440\u0445\u0438\u0432\u043d\u043e\u0439 \u0432\u0435\u0442\u043a\u0435. \u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438', max_length=255, null=True, verbose_name='URL \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0430\u0440\u0445\u0438\u0432\u043d\u043e\u0433\u043e \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430')),
                ('youtube_duration', models.CharField(blank=True, help_text='\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0432\u0438\u0434\u0435\u043e \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430. \u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438', max_length=10, null=True, verbose_name='\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430')),
                ('youtube_views_count', models.PositiveIntegerField(blank=True, default=0, help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u0432\u0438\u0434\u0435\u043e \u043d\u0430 YouTube. \u041e\u0431\u043d\u043e\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438', null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432')),
                ('start_at', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('finish_at', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('seo_title', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_ru', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_uk', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_title_hu', models.CharField(blank=True, help_text='Title \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Title')),
                ('seo_description', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_ru', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_uk', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_description_hu', models.CharField(blank=True, help_text='Description \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Description')),
                ('seo_keywords', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_uk', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('seo_keywords_hu', models.CharField(blank=True, help_text='Keywords \u043f\u0440\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u0435\u0431\u0438\u043d\u0430\u0440\u0430', max_length=255, null=True, verbose_name='(SEO) Keywords')),
                ('speakers', models.ManyToManyField(blank=True, to='webinars.Speaker', verbose_name='\u0421\u043f\u0438\u043a\u0435\u0440\u044b')),
            ],
            options={
                'ordering': ('start_at',),
                'verbose_name': '\u0412\u0435\u0431\u0438\u043d\u0430\u0440',
                'verbose_name_plural': '\u0412\u0435\u0431\u0438\u043d\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='WebinarReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='\u044f\u0437\u044b\u043a \u043f\u0440\u0438 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0438\u043c\u044f')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('city', models.CharField(max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('is_sent_email', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e \u043f\u0438\u0441\u044c\u043c\u043e?')),
                ('is_sent_sms', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e \u0421\u041c\u0421?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='webinars.Webinar', verbose_name='\u0412\u0435\u0431\u0438\u043d\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044e \u043d\u0430 \u0432\u0435\u0431\u0438\u043d\u0430\u0440',
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='seminarvideo',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='webinars.Webinar', verbose_name='\u0412\u0435\u0431\u0438\u043d\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='seminarphoto',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webinars.Webinar', verbose_name='\u0412\u0435\u0431\u0438\u043d\u0430\u0440'),
        ),
    ]
