# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCachedPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, verbose_name='\u041a\u0435\u0448\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430')),
                ('phrase_ru', models.CharField(max_length=255, null=True, verbose_name='\u041a\u0435\u0448\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430')),
                ('phrase_uk', models.CharField(max_length=255, null=True, verbose_name='\u041a\u0435\u0448\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430')),
                ('phrase_hu', models.CharField(max_length=255, null=True, verbose_name='\u041a\u0435\u0448\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430')),
                ('hash_string', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u0425\u044d\u0448 \u0440\u0443\u0441\u0441\u043a\u043e\u0439 \u0441\u0442\u0440\u043e\u043a\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='SEORule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='\u0412\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0435\u0435 \u0438\u043c\u044f \u043f\u0440\u0430\u0432\u0438\u043b\u0430')),
                ('deal_type', models.CharField(choices=[(b'deafult', '\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e'), (b'sale', '\u041a\u0443\u043f\u0438\u0442\u044c'), (b'rent', '\u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u0430\u044f \u0430\u0440\u0435\u043d\u0434\u0430'), (b'rent_daily', '\u0410\u0440\u0435\u043d\u0434\u0430 \u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e'), (b'newhomes', '\u041d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439\u043a\u0438'), (b'index', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430')], default=b'default', max_length=12, verbose_name='\u0422\u0438\u043f \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('region_kind', models.CharField(choices=[(b'default', '\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e'), (b'country', '\u0421\u0442\u0440\u0430\u043d\u0430'), (b'province', '\u041f\u0440\u043e\u0432\u0438\u043d\u0446\u0438\u044f'), (b'area', '\u041e\u0431\u043b\u0430\u0441\u0442\u044c'), (b'locality', '\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442'), (b'village', '\u0421\u0435\u043b\u043e'), (b'district', '\u0420\u0430\u0439\u043e\u043d'), (b'street', '\u0423\u043b\u0438\u0446\u0430')], default=b'default', max_length=12, verbose_name='\u0422\u0438\u043f \u0440\u0435\u0433\u0438\u043e\u043d\u0430')),
                ('subpage', models.CharField(choices=[(b'default', '\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e'), (b'streets', '\u0421\u043f\u0438\u0441\u043e\u043a \u0443\u043b\u0438\u0446'), (b'metro_stations', '\u0421\u043f\u0438\u0441\u043e\u043a \u0441\u0442\u0430\u043d\u0446\u0438\u0439 \u043c\u0435\u0442\u0440\u043e')], default=b'default', max_length=15, verbose_name='\u041f\u043e\u0434\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b  \u0440\u0430\u0437\u0434\u0435\u043b\u0430')),
                ('property_type', models.CharField(choices=[(b'default', '\u041f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e (\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0430)'), (b'room', '\u041a\u043e\u043c\u043d\u0430\u0442\u0430'), (b'house', '\u0414\u043e\u043c'), (b'commercial', '\u041a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0430\u044f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c'), (b'plot', '\u0423\u0447\u0430\u0441\u0442\u043e\u043a'), (b'garages', '\u0413\u0430\u0440\u0430\u0436'), (b'all-real-estate', '\u041d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c')], default=b'default', max_length=20, verbose_name='\u0422\u0438\u043f \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
                ('check_rooms', models.BooleanField(default=False, help_text='\u0420\u0430\u0431\u043e\u0442\u0430\u0435\u0442 \u0442\u043e\u043b\u044c\u043a\u043e \u0434\u043b\u044f \u0442\u0438\u043f\u043e\u0432 \u043e\u0431\u044a\u0435\u043a\u0442\u0430: \u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430 \u0438\u043b\u0438 \u0414\u043e\u043c + \u0443\u043a\u0430\u0437\u0430\u043d\u043e \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043e\u043c\u043d\u0430\u0442 \u0432 \u043f\u043e\u0438\u0441\u043a\u0435', verbose_name='\u0423\u0447\u0438\u0442\u044b\u0432\u0430\u0442\u044c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043e\u043c\u043d\u0430\u0442 \u043f\u0440\u0438 \u0444\u0438\u043b\u044c\u0442\u0440\u0430\u0446\u0438\u0438?')),
                ('check_subway', models.BooleanField(default=False, verbose_name='\u0423\u0447\u0438\u0442\u044b\u0432\u0430\u0442\u044c \u043c\u0435\u0442\u0440\u043e \u043f\u0440\u0438 \u0444\u0438\u043b\u044c\u0442\u0440\u0430\u0446\u0438\u0438?')),
                ('check_not_main_city', models.BooleanField(default=False, verbose_name='\u0413\u043e\u0440\u043e\u0434, \u043d\u0435 \u043e\u0431\u043b\u0430\u0441\u0442\u043d\u043e\u0439 \u0446\u0435\u043d\u0442\u0440, \u0431\u0435\u0437 \u0441\u0443\u0431\u0434\u043e\u043c\u0435\u043d\u0430')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('description_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('description_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('keywords_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('keywords_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('keywords_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('h1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('h1_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('h1_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1')),
                ('crosslink_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u043f\u0435\u0440\u0435\u043b\u0438\u043d\u043a\u043e\u0432\u043a\u0438')),
                ('crosslink_header_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u043f\u0435\u0440\u0435\u043b\u0438\u043d\u043a\u043e\u0432\u043a\u0438')),
                ('crosslink_header_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u043f\u0435\u0440\u0435\u043b\u0438\u043d\u043a\u043e\u0432\u043a\u0438')),
                ('crosslink_header_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u043f\u0435\u0440\u0435\u043b\u0438\u043d\u043a\u043e\u0432\u043a\u0438')),
            ],
            options={
                'verbose_name': 'SEO \u043f\u0440\u0430\u0432\u0438\u043b\u043e',
                'verbose_name_plural': 'SEO \u043f\u0440\u0430\u0432\u0438\u043b\u0430',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('text', models.TextField(blank=True, default=b'', verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textblocks', to='ad.Region', verbose_name='\u0440\u0435\u0433\u0438\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u0442\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439 \u0431\u043b\u043e\u043a',
                'verbose_name_plural': '\u0442\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0435 \u0431\u043b\u043e\u043a\u0438',
            },
        ),
    ]
