# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

import agency.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=agency.models.make_agency_upload_path, verbose_name='\u043b\u043e\u0433\u043e\u0442\u0438\u043f')),
                ('city_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0433\u043e\u0440\u043e\u0434 (\u0441\u0442\u0430\u0440\u043e\u0435 \u043f\u043e\u043b\u0435)')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0430\u0434\u0440\u0435\u0441')),
                ('show_in_agencies', models.BooleanField(default=True, verbose_name='\u043f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u043e \u0432 \u0440\u0430\u0437\u0434\u0435\u043b\u0435 \u0441\u0430\u0439\u0442\u0430 "\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u044b"')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('site', models.URLField(blank=True, help_text='\u0430\u0434\u0440\u0435\u0441 \u0434\u043e\u043b\u0436\u0435\u043d \u043d\u0430\u0447\u0438\u043d\u0430\u0442\u044c\u0441\u044f \u0441 http://', max_length=100, null=True, verbose_name='\u0432\u0435\u0431-\u0441\u0430\u0439\u0442')),
                ('import_url', models.URLField(blank=True, max_length=100, null=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u0434\u043b\u044f \u0438\u043c\u043f\u043e\u0440\u0442\u0430')),
                ('asnu_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0432\u0438\u0434\u0435\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430 \u0410\u0421\u041d\u0423')),
                ('import_report_access_code', models.CharField(default=agency.models.make_uuid_hex, max_length=32, unique=True, verbose_name='\u043a\u043e\u0434 \u0434\u043e\u0441\u0442\u0443\u043f\u0430 \u043a \u043e\u0442\u0447\u0435\u0442\u0430\u043c \u0438\u043c\u043f\u043e\u0440\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[(b'new', '\u041f\u0435\u0440\u0432\u0438\u0447\u043d\u044b\u0439 \u043a\u043e\u043d\u0442\u0430\u043a\u0442'), (b'in_progress', '\u0412 \u0440\u0430\u0431\u043e\u0442\u0435'), (b'awaiting', '\u041f\u0440\u0438\u043d\u0438\u043c\u0430\u0435\u0442 \u0440\u0435\u0448\u0435\u043d\u0438\u0435'), (b'success', '\u0421\u0434\u0435\u043b\u043a\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430'), (b'fail', '\u0421\u0434\u0435\u043b\u043a\u0430 \u043d\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043b\u0430\u0441\u044c')], default=b'new', max_length=50, verbose_name='\u043c\u0435\u0442\u043a\u0430')),
                ('name', models.CharField(blank=True, max_length=61, null=True, verbose_name='\u0438\u043c\u044f')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('is_readed', models.BooleanField(default=False, verbose_name='\u043f\u0440\u043e\u0447\u0438\u0442\u0430\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u043b\u0438\u0434',
                'verbose_name_plural': '\u043b\u0438\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='LeadHistoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('event', agency.models.JSONField(blank=True, verbose_name='\u0441\u043e\u0431\u044b\u0442\u0438\u0435')),
                ('is_readed', models.BooleanField(default=False, verbose_name='\u043f\u0440\u043e\u0447\u0438\u0442\u0430\u043d\u043e')),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('-time',),
                'verbose_name': '\u0441\u043e\u0431\u044b\u0442\u0438\u0435 \u043b\u0438\u0434\u0430',
                'verbose_name_plural': '\u0441\u043e\u0431\u044b\u0442\u0438\u044f \u043b\u0438\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0437\u0430\u043c\u0435\u0442\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043c\u0435\u0442\u043a\u0430 \u043a \u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0443',
                'verbose_name_plural': '\u0437\u0430\u043c\u0435\u0442\u043a\u0438 \u043a \u0440\u0438\u0435\u043b\u0442\u043e\u0440\u0443',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='\u0430\u0434\u043c\u0438\u043d \u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u0430?')),
                ('is_active', models.NullBooleanField(default=False, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439?')),
                ('confirmation_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u043a\u043e\u0434 \u0434\u043b\u044f \u0441\u0441\u044b\u043b\u043a\u0438 \u0430\u043a\u0442\u0438\u0432\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0440\u0438\u0435\u043b\u0442\u043e\u0440',
                'verbose_name_plural': '\u0440\u0438\u0435\u043b\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='\u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('end', models.DateTimeField(verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('name', models.CharField(max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='\u0437\u0430\u043c\u0435\u0442\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u0434\u0430\u0447\u0430',
                'verbose_name_plural': '\u0437\u0430\u0434\u0430\u0447\u0438',
            },
        ),
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('professionals_contacts_views', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043e\u0432 \u0432 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u0430\u0445')),
            ],
            options={
                'verbose_name': '\u0441\u0447\u0435\u0442\u0447\u0438\u043a \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0438 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
            },
        ),
    ]
