# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('ad', '0002_auto_20161229_0023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewscounts', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='task',
            name='basead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u0435\u043a\u0442 (\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435)'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Lead', verbose_name='\u043b\u0438\u0434'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='\u0432\u043b\u0430\u0434\u0435\u043b\u0435\u0446'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to='agency.Agency', verbose_name='\u0430\u0433\u0435\u043d\u0442\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='note',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='agency.Realtor', verbose_name='\u0440\u0438\u0435\u043b\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_notes', to=settings.AUTH_USER_MODEL, verbose_name='\u0432\u043b\u0430\u0434\u0435\u043b\u0435\u0446 \u0437\u0430\u043c\u0435\u0442\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='leadhistoryevent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='leadhistoryevent',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agency.Lead', verbose_name='\u043b\u0438\u0434'),
        ),
        migrations.AddField(
            model_name='lead',
            name='basead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.BaseAd', verbose_name='\u043e\u0431\u044a\u0435\u043a\u0442 (\u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='\u0432\u043b\u0430\u0434\u0435\u043b\u0435\u0446 \u043b\u0438\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.Region', verbose_name='\u0433\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='agency',
            name='deal_types',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='ad.DealType', verbose_name='\u0442\u0438\u043f\u044b \u0441\u0434\u0435\u043b\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='agency',
            name='users',
            field=models.ManyToManyField(related_name='agencies', through='agency.Realtor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='realtor',
            unique_together=set([('agency', 'user')]),
        ),
    ]
