# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[(b'top', '\u0441\u0432\u0435\u0440\u0445\u0443 (728x90)'), (b'right', '\u0441\u043f\u0440\u0430\u0432\u0430 (120x600)'), (b'bottom', '\u0441\u043d\u0438\u0437\u0443 (728x90)'), (b'mainpage', '\u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 (255x255)'), (b'subdomain', '\u043d\u0430 \u043f\u043e\u0434\u0434\u043e\u043c\u0435\u043d\u0430\u0445 (250x250)'), (b'property', '\u0432 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f\u0445 (180x100)')], default=b'top', max_length=20, verbose_name='\u043c\u0435\u0441\u0442\u043e')),
                ('type', models.CharField(choices=[(b'image', '\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'), (b'swf', '\u0444\u043b\u0435\u0448 (swf)'), (b'html', 'HTML \u043a\u043e\u0434')], default=b'image', max_length=10, verbose_name='\u0442\u0438\u043f \u0431\u0430\u043d\u043d\u0435\u0440\u0430')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'upload/banner', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('swf', models.FileField(blank=True, null=True, upload_to=b'upload/banner', verbose_name='\u0444\u043b\u0435\u0448 (swf)')),
                ('html', models.TextField(blank=True, null=True, verbose_name='\u0432\u043d\u0435\u0448\u043d\u0438\u0439 \u043a\u043e\u0434')),
                ('url', models.URLField(blank=True, help_text='\u043f\u0440\u0438 \u043d\u0435\u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u043d\u043e\u043c \u043f\u043e\u043b\u0435 \u0431\u0430\u043d\u043d\u0435\u0440 \u0431\u0443\u0434\u0435\u0442 \u043d\u0435\u043a\u043b\u0438\u043a\u0430\u0431\u0435\u043b\u044c\u043d\u044b\u043c', null=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('pages', models.CharField(choices=[(b'free', '\u043d\u0435\u0437\u0430\u043d\u044f\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'), (b'mainpage', '\u0433\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'), (b'subdomains', '\u0432\u044b\u0431\u0440\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u0434\u0434\u043e\u043c\u0435\u043d\u044b')], default=b'free', max_length=30, verbose_name='\u0433\u0440\u0443\u043f\u043f\u044b \u0441\u0442\u0440\u0430\u043d\u0438\u0446')),
                ('deal_type', models.CharField(blank=True, choices=[(b'rent', '\u0430\u0440\u0435\u043d\u0434\u0430'), (b'rent_daily', '\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0430\u0440\u0435\u043d\u0434\u0430'), (b'sale', '\u043f\u0440\u043e\u0434\u0430\u0436\u0430')], max_length=20, null=True, verbose_name='\u0442\u0438\u043f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438')),
                ('property_type', models.CharField(blank=True, choices=[(b'flat', '\u043a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), (b'room', '\u043a\u043e\u043c\u043d\u0430\u0442\u0430'), (b'house', '\u0434\u043e\u043c'), (b'plot', '\u0443\u0447\u0430\u0441\u0442\u043e\u043a'), (b'commercial', '\u043a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u0430\u044f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c'), (b'garages', '\u0433\u0430\u0440\u0430\u0436\u0438')], max_length=20, null=True, verbose_name='\u0442\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name=b'\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c \xd1\x81')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name=b'\xd0\xb4\xd0\xbe')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u044b\u0439')),
            ],
            options={
                'verbose_name': '\u0431\u0430\u043d\u043d\u0435\u0440',
                'verbose_name_plural': '\u0431\u0430\u043d\u043d\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='BannerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='\u043f\u043e\u043a\u0430\u0437\u044b')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='\u043a\u043b\u0438\u043a\u0438')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.Banner', verbose_name=b'\xd0\xb1\xd0\xb0\xd0\xbd\xd0\xbd\xd0\xb5\xd1\x80')),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('representatives', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0438\u043c\u044f \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0432\u0435\u0431-\u0441\u0430\u0439\u0442')),
            ],
            options={
                'verbose_name': '\u0440\u0435\u043a\u043b\u0430\u043c\u043d\u0430\u044f \u043a\u0430\u043c\u043f\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0440\u0435\u043a\u043b\u0430\u043c\u043d\u044b\u0435 \u043a\u0430\u043c\u043f\u0430\u043d\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.Campaign', verbose_name='\u0440\u0435\u043a\u043b\u0430\u043c\u043d\u0430\u044f \u043a\u0430\u043c\u043f\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subdomains',
            field=models.ManyToManyField(blank=True, to='ad.Region', verbose_name='\u043f\u043e\u0434\u0434\u043e\u043c\u0435\u043d\u044b'),
        ),
        migrations.AlterUniqueTogether(
            name='bannerstats',
            unique_together=set([('banner', 'date')]),
        ),
    ]
