# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 12:59
from __future__ import unicode_literals

from django.db import migrations


def delete_related_django_objects(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get(id=5).delete()

    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    for ct in ContentType.objects.filter(app_label='banner'):
        Permission.objects.filter(content_type=ct).delete()
        ct.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subdomains',
        ),
        migrations.AlterUniqueTogether(
            name='bannerstats',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bannerstats',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerStats',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.RunPython(delete_related_django_objects, migrations.RunPython.noop),
    ]
