# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 17:54
from __future__ import unicode_literals

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banner', '0002_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u0430\u043a\u0442\u0438\u0432\u043d\u043e')),
                ('image', models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('image_ru', models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('image_uk', models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('image_hu', models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('url', models.URLField(blank=True, max_length=512, verbose_name=b'\xd1\x81\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u0431\u0430\u043d\u043d\u0435\u0440 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430',
                'verbose_name_plural': '\u0431\u0430\u043d\u043d\u0435\u0440\u044b \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430',
            },
        ),
    ]
