# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_sliderbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderbanner',
            name='link_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='\u043a\u043b\u0438\u043a\u0438 \u043f\u043e \u0441\u0441\u044b\u043b\u043a\u0430\u043c'),
        ),
    ]
