# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_sliderbanner_link_clicks'),
    ]

    operations = [
        migrations.RenameModel("SliderBanner", "Banner")
    ]
