# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 02:42
from __future__ import unicode_literals

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20171201_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '\u0431\u0430\u043d\u043d\u0435\u0440', 'verbose_name_plural': '\u0431\u0430\u043d\u043d\u0435\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='banner',
            name='image_bg',
            field=models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0444\u043e\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_bg_hu',
            field=models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0444\u043e\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_bg_ru',
            field=models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0444\u043e\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_bg_uk',
            field=models.FileField(blank=True, null=True, upload_to=banner.models.make_call_upload_path, verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0444\u043e\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='place',
            field=models.CharField(choices=[(b'slider', '\u0441\u043b\u0430\u0439\u0434\u0435\u0440 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439'), (b'topline', 'topline'), (b'catfish', 'catfish')], default='slider', max_length=10, verbose_name='\u0431\u0430\u043d\u043d\u0435\u0440\u043d\u043e\u0435 \u043c\u0435\u0441\u0442\u043e'),
            preserve_default=False,
        ),
    ]
