# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20171201_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='\u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u043b\u0438\u043a\u043e\u0432')),
            ],
            options={
                'verbose_name': '\u043a\u043b\u0438\u043a \u043f\u043e \u0431\u0430\u043d\u043d\u0435\u0440\u0443',
                'verbose_name_plural': '\u043a\u043b\u0438\u043a\u0438 \u043f\u043e \u0431\u0430\u043d\u043d\u0435\u0440\u0443',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u0435 \u043f\u043e\u043a\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e \u043f\u043e\u043a\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='targeting_pages',
            field=models.TextField(blank=True, null=True, verbose_name='\u043f\u043e\u043a\u0430\u0437 \u0442\u043e\u043b\u044c\u043a\u043e \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='bannerclick',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='banner.Banner', verbose_name='\u0431\u0430\u043d\u043d\u0435\u0440'),
        ),
    ]
